# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tinyI2C.ui'
#
# Created: Mon Jan 19 14:45:40 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import hexSpinbox

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(710, 772)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.conport_box = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.conport_box.setFont(font)
        self.conport_box.setFlat(False)
        self.conport_box.setCheckable(False)
        self.conport_box.setObjectName(_fromUtf8("conport_box"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.conport_box)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.getPortBtn = QtGui.QPushButton(self.conport_box)
        self.getPortBtn.setObjectName(_fromUtf8("getPortBtn"))
        self.horizontalLayout.addWidget(self.getPortBtn)
        self.portList = QtGui.QComboBox(self.conport_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.portList.setFont(font)
        self.portList.setObjectName(_fromUtf8("portList"))
        self.horizontalLayout.addWidget(self.portList)
        self.gridLayout.addWidget(self.conport_box, 0, 0, 1, 1)
        self.log_box = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.log_box.setFont(font)
        self.log_box.setObjectName(_fromUtf8("log_box"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.log_box)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.log_text = QtGui.QPlainTextEdit(self.log_box)
        self.log_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.log_text.setObjectName(_fromUtf8("log_text"))
        self.verticalLayout_9.addWidget(self.log_text)
        self.gridLayout.addWidget(self.log_box, 5, 0, 1, 1)
        self.i2c_box = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i2c_box.setFont(font)
        self.i2c_box.setObjectName(_fromUtf8("i2c_box"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.i2c_box)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.i2c1_box = QtGui.QGroupBox(self.i2c_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i2c1_box.setFont(font)
        self.i2c1_box.setObjectName(_fromUtf8("i2c1_box"))
        self.verticalLayout = QtGui.QVBoxLayout(self.i2c1_box)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.base_CH1 = hexSpinbox.HexSpinBox(self.i2c1_box)
        self.base_CH1.setSuffix(_fromUtf8(""))
        self.base_CH1.setPrefix(_fromUtf8(""))
        self.base_CH1.setMaximum(255)
        self.base_CH1.setSingleStep(2)
        self.base_CH1.setProperty("value", 144)
        self.base_CH1.setObjectName(_fromUtf8("base_CH1"))
        self.verticalLayout.addWidget(self.base_CH1)
        self.reg_CH1 = hexSpinbox.HexSpinBox(self.i2c1_box)
        self.reg_CH1.setSuffix(_fromUtf8(""))
        self.reg_CH1.setPrefix(_fromUtf8(""))
        self.reg_CH1.setMaximum(255)
        self.reg_CH1.setObjectName(_fromUtf8("reg_CH1"))
        self.verticalLayout.addWidget(self.reg_CH1)
        self.readbtn_CH1 = QtGui.QPushButton(self.i2c1_box)
        self.readbtn_CH1.setObjectName(_fromUtf8("readbtn_CH1"))
        self.verticalLayout.addWidget(self.readbtn_CH1)
        self.read_CH1 = hexSpinbox.HexSpinBox(self.i2c1_box)
        self.read_CH1.setEnabled(False)
        self.read_CH1.setSuffix(_fromUtf8(""))
        self.read_CH1.setPrefix(_fromUtf8(""))
        self.read_CH1.setMaximum(255)
        self.read_CH1.setObjectName(_fromUtf8("read_CH1"))
        self.verticalLayout.addWidget(self.read_CH1)
        self.writebtn_CH1 = QtGui.QPushButton(self.i2c1_box)
        self.writebtn_CH1.setObjectName(_fromUtf8("writebtn_CH1"))
        self.verticalLayout.addWidget(self.writebtn_CH1)
        self.write_CH1 = hexSpinbox.HexSpinBox(self.i2c1_box)
        self.write_CH1.setSuffix(_fromUtf8(""))
        self.write_CH1.setPrefix(_fromUtf8(""))
        self.write_CH1.setMaximum(255)
        self.write_CH1.setObjectName(_fromUtf8("write_CH1"))
        self.verticalLayout.addWidget(self.write_CH1)
        self.horizontalLayout_6.addWidget(self.i2c1_box)
        self.i2c2_box = QtGui.QGroupBox(self.i2c_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i2c2_box.setFont(font)
        self.i2c2_box.setObjectName(_fromUtf8("i2c2_box"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.i2c2_box)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.base_CH2 = hexSpinbox.HexSpinBox(self.i2c2_box)
        self.base_CH2.setSuffix(_fromUtf8(""))
        self.base_CH2.setPrefix(_fromUtf8(""))
        self.base_CH2.setMaximum(255)
        self.base_CH2.setSingleStep(2)
        self.base_CH2.setProperty("value", 144)
        self.base_CH2.setObjectName(_fromUtf8("base_CH2"))
        self.verticalLayout_5.addWidget(self.base_CH2)
        self.reg_CH2 = hexSpinbox.HexSpinBox(self.i2c2_box)
        self.reg_CH2.setSuffix(_fromUtf8(""))
        self.reg_CH2.setPrefix(_fromUtf8(""))
        self.reg_CH2.setMaximum(255)
        self.reg_CH2.setObjectName(_fromUtf8("reg_CH2"))
        self.verticalLayout_5.addWidget(self.reg_CH2)
        self.readbtn_CH2 = QtGui.QPushButton(self.i2c2_box)
        self.readbtn_CH2.setObjectName(_fromUtf8("readbtn_CH2"))
        self.verticalLayout_5.addWidget(self.readbtn_CH2)
        self.read_CH2 = hexSpinbox.HexSpinBox(self.i2c2_box)
        self.read_CH2.setEnabled(False)
        self.read_CH2.setSuffix(_fromUtf8(""))
        self.read_CH2.setPrefix(_fromUtf8(""))
        self.read_CH2.setMaximum(255)
        self.read_CH2.setObjectName(_fromUtf8("read_CH2"))
        self.verticalLayout_5.addWidget(self.read_CH2)
        self.writebtn_CH2 = QtGui.QPushButton(self.i2c2_box)
        self.writebtn_CH2.setObjectName(_fromUtf8("writebtn_CH2"))
        self.verticalLayout_5.addWidget(self.writebtn_CH2)
        self.write_CH2 = hexSpinbox.HexSpinBox(self.i2c2_box)
        self.write_CH2.setSuffix(_fromUtf8(""))
        self.write_CH2.setPrefix(_fromUtf8(""))
        self.write_CH2.setMaximum(255)
        self.write_CH2.setObjectName(_fromUtf8("write_CH2"))
        self.verticalLayout_5.addWidget(self.write_CH2)
        self.horizontalLayout_6.addWidget(self.i2c2_box)
        self.i2c3_box = QtGui.QGroupBox(self.i2c_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i2c3_box.setFont(font)
        self.i2c3_box.setObjectName(_fromUtf8("i2c3_box"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.i2c3_box)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.base_CH3 = hexSpinbox.HexSpinBox(self.i2c3_box)
        self.base_CH3.setSuffix(_fromUtf8(""))
        self.base_CH3.setPrefix(_fromUtf8(""))
        self.base_CH3.setMaximum(255)
        self.base_CH3.setSingleStep(2)
        self.base_CH3.setProperty("value", 144)
        self.base_CH3.setObjectName(_fromUtf8("base_CH3"))
        self.verticalLayout_6.addWidget(self.base_CH3)
        self.reg_CH3 = hexSpinbox.HexSpinBox(self.i2c3_box)
        self.reg_CH3.setSuffix(_fromUtf8(""))
        self.reg_CH3.setPrefix(_fromUtf8(""))
        self.reg_CH3.setMaximum(255)
        self.reg_CH3.setObjectName(_fromUtf8("reg_CH3"))
        self.verticalLayout_6.addWidget(self.reg_CH3)
        self.readbtn_CH3 = QtGui.QPushButton(self.i2c3_box)
        self.readbtn_CH3.setObjectName(_fromUtf8("readbtn_CH3"))
        self.verticalLayout_6.addWidget(self.readbtn_CH3)
        self.read_CH3 = hexSpinbox.HexSpinBox(self.i2c3_box)
        self.read_CH3.setEnabled(False)
        self.read_CH3.setSuffix(_fromUtf8(""))
        self.read_CH3.setPrefix(_fromUtf8(""))
        self.read_CH3.setMaximum(255)
        self.read_CH3.setObjectName(_fromUtf8("read_CH3"))
        self.verticalLayout_6.addWidget(self.read_CH3)
        self.writebtn_CH3 = QtGui.QPushButton(self.i2c3_box)
        self.writebtn_CH3.setObjectName(_fromUtf8("writebtn_CH3"))
        self.verticalLayout_6.addWidget(self.writebtn_CH3)
        self.write_CH3 = hexSpinbox.HexSpinBox(self.i2c3_box)
        self.write_CH3.setSuffix(_fromUtf8(""))
        self.write_CH3.setPrefix(_fromUtf8(""))
        self.write_CH3.setMaximum(255)
        self.write_CH3.setObjectName(_fromUtf8("write_CH3"))
        self.verticalLayout_6.addWidget(self.write_CH3)
        self.horizontalLayout_6.addWidget(self.i2c3_box)
        self.i2c4_box = QtGui.QGroupBox(self.i2c_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i2c4_box.setFont(font)
        self.i2c4_box.setObjectName(_fromUtf8("i2c4_box"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.i2c4_box)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.base_CH4 = hexSpinbox.HexSpinBox(self.i2c4_box)
        self.base_CH4.setSuffix(_fromUtf8(""))
        self.base_CH4.setPrefix(_fromUtf8(""))
        self.base_CH4.setMaximum(255)
        self.base_CH4.setSingleStep(2)
        self.base_CH4.setProperty("value", 144)
        self.base_CH4.setObjectName(_fromUtf8("base_CH4"))
        self.verticalLayout_7.addWidget(self.base_CH4)
        self.reg_CH4 = hexSpinbox.HexSpinBox(self.i2c4_box)
        self.reg_CH4.setSuffix(_fromUtf8(""))
        self.reg_CH4.setPrefix(_fromUtf8(""))
        self.reg_CH4.setMaximum(255)
        self.reg_CH4.setObjectName(_fromUtf8("reg_CH4"))
        self.verticalLayout_7.addWidget(self.reg_CH4)
        self.readbtn_CH4 = QtGui.QPushButton(self.i2c4_box)
        self.readbtn_CH4.setObjectName(_fromUtf8("readbtn_CH4"))
        self.verticalLayout_7.addWidget(self.readbtn_CH4)
        self.read_CH4 = hexSpinbox.HexSpinBox(self.i2c4_box)
        self.read_CH4.setEnabled(False)
        self.read_CH4.setSuffix(_fromUtf8(""))
        self.read_CH4.setPrefix(_fromUtf8(""))
        self.read_CH4.setMaximum(255)
        self.read_CH4.setObjectName(_fromUtf8("read_CH4"))
        self.verticalLayout_7.addWidget(self.read_CH4)
        self.writebtn_CH4 = QtGui.QPushButton(self.i2c4_box)
        self.writebtn_CH4.setObjectName(_fromUtf8("writebtn_CH4"))
        self.verticalLayout_7.addWidget(self.writebtn_CH4)
        self.write_CH4 = hexSpinbox.HexSpinBox(self.i2c4_box)
        self.write_CH4.setSuffix(_fromUtf8(""))
        self.write_CH4.setPrefix(_fromUtf8(""))
        self.write_CH4.setMaximum(255)
        self.write_CH4.setObjectName(_fromUtf8("write_CH4"))
        self.verticalLayout_7.addWidget(self.write_CH4)
        self.horizontalLayout_6.addWidget(self.i2c4_box)
        self.spi_box = QtGui.QGroupBox(self.i2c_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spi_box.setFont(font)
        self.spi_box.setObjectName(_fromUtf8("spi_box"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.spi_box)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.base_SPI = hexSpinbox.HexSpinBox(self.spi_box)
        self.base_SPI.setSuffix(_fromUtf8(""))
        self.base_SPI.setPrefix(_fromUtf8(""))
        self.base_SPI.setMaximum(255)
        self.base_SPI.setProperty("value", 144)
        self.base_SPI.setObjectName(_fromUtf8("base_SPI"))
        self.verticalLayout_10.addWidget(self.base_SPI)
        self.reg_SPI = hexSpinbox.HexSpinBox(self.spi_box)
        self.reg_SPI.setSuffix(_fromUtf8(""))
        self.reg_SPI.setPrefix(_fromUtf8(""))
        self.reg_SPI.setMaximum(255)
        self.reg_SPI.setObjectName(_fromUtf8("reg_SPI"))
        self.verticalLayout_10.addWidget(self.reg_SPI)
        self.readbtn_SPI = QtGui.QPushButton(self.spi_box)
        self.readbtn_SPI.setObjectName(_fromUtf8("readbtn_SPI"))
        self.verticalLayout_10.addWidget(self.readbtn_SPI)
        self.read_SPI = hexSpinbox.HexSpinBox(self.spi_box)
        self.read_SPI.setEnabled(False)
        self.read_SPI.setSuffix(_fromUtf8(""))
        self.read_SPI.setPrefix(_fromUtf8(""))
        self.read_SPI.setMaximum(255)
        self.read_SPI.setObjectName(_fromUtf8("read_SPI"))
        self.verticalLayout_10.addWidget(self.read_SPI)
        self.writebtn_SPI = QtGui.QPushButton(self.spi_box)
        self.writebtn_SPI.setObjectName(_fromUtf8("writebtn_SPI"))
        self.verticalLayout_10.addWidget(self.writebtn_SPI)
        self.write_SPI = hexSpinbox.HexSpinBox(self.spi_box)
        self.write_SPI.setSuffix(_fromUtf8(""))
        self.write_SPI.setPrefix(_fromUtf8(""))
        self.write_SPI.setMaximum(255)
        self.write_SPI.setObjectName(_fromUtf8("write_SPI"))
        self.verticalLayout_10.addWidget(self.write_SPI)
        self.horizontalLayout_6.addWidget(self.spi_box)
        self.gridLayout.addWidget(self.i2c_box, 1, 0, 1, 1)
        self.regixters_box = QtGui.QGroupBox(Form)
        self.regixters_box.setObjectName(_fromUtf8("regixters_box"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.regixters_box)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.registers_tab = QtGui.QTabWidget(self.regixters_box)
        self.registers_tab.setObjectName(_fromUtf8("registers_tab"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.reg0_box = QtGui.QGroupBox(self.tab)
        self.reg0_box.setObjectName(_fromUtf8("reg0_box"))
        self.gridLayout_2 = QtGui.QGridLayout(self.reg0_box)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.reg07 = QtGui.QCheckBox(self.reg0_box)
        self.reg07.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg07.setFont(font)
        self.reg07.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.reg07.setObjectName(_fromUtf8("reg07"))
        self.gridLayout_2.addWidget(self.reg07, 1, 0, 1, 1)
        self.reg06 = QtGui.QCheckBox(self.reg0_box)
        self.reg06.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg06.setFont(font)
        self.reg06.setObjectName(_fromUtf8("reg06"))
        self.gridLayout_2.addWidget(self.reg06, 1, 1, 1, 1)
        self.reg05 = QtGui.QCheckBox(self.reg0_box)
        self.reg05.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg05.setFont(font)
        self.reg05.setObjectName(_fromUtf8("reg05"))
        self.gridLayout_2.addWidget(self.reg05, 1, 2, 1, 1)
        self.reg04 = QtGui.QCheckBox(self.reg0_box)
        self.reg04.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg04.setFont(font)
        self.reg04.setObjectName(_fromUtf8("reg04"))
        self.gridLayout_2.addWidget(self.reg04, 1, 3, 1, 1)
        self.reg03 = QtGui.QCheckBox(self.reg0_box)
        self.reg03.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg03.setFont(font)
        self.reg03.setObjectName(_fromUtf8("reg03"))
        self.gridLayout_2.addWidget(self.reg03, 1, 4, 1, 1)
        self.reg02 = QtGui.QCheckBox(self.reg0_box)
        self.reg02.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg02.setFont(font)
        self.reg02.setObjectName(_fromUtf8("reg02"))
        self.gridLayout_2.addWidget(self.reg02, 1, 5, 1, 1)
        self.reg01 = QtGui.QCheckBox(self.reg0_box)
        self.reg01.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg01.setFont(font)
        self.reg01.setObjectName(_fromUtf8("reg01"))
        self.gridLayout_2.addWidget(self.reg01, 1, 6, 1, 1)
        self.reg00 = QtGui.QCheckBox(self.reg0_box)
        self.reg00.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg00.setFont(font)
        self.reg00.setObjectName(_fromUtf8("reg00"))
        self.gridLayout_2.addWidget(self.reg00, 1, 7, 1, 1)
        self.readbtn_reg0 = QtGui.QPushButton(self.reg0_box)
        self.readbtn_reg0.setObjectName(_fromUtf8("readbtn_reg0"))
        self.gridLayout_2.addWidget(self.readbtn_reg0, 1, 8, 1, 1)
        self.read_reg0 = hexSpinbox.HexSpinBox(self.reg0_box)
        self.read_reg0.setEnabled(False)
        self.read_reg0.setMaximum(255)
        self.read_reg0.setObjectName(_fromUtf8("read_reg0"))
        self.gridLayout_2.addWidget(self.read_reg0, 1, 9, 1, 1)
        self.writebtn_reg0 = QtGui.QPushButton(self.reg0_box)
        self.writebtn_reg0.setEnabled(False)
        self.writebtn_reg0.setObjectName(_fromUtf8("writebtn_reg0"))
        self.gridLayout_2.addWidget(self.writebtn_reg0, 1, 10, 1, 1)
        self.write_reg0 = hexSpinbox.HexSpinBox(self.reg0_box)
        self.write_reg0.setEnabled(False)
        self.write_reg0.setMaximum(255)
        self.write_reg0.setObjectName(_fromUtf8("write_reg0"))
        self.gridLayout_2.addWidget(self.write_reg0, 1, 11, 1, 1)
        self.label = QtGui.QLabel(self.reg0_box)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.reg0_box)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.reg0_box)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.reg0_box)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.reg0_box)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.reg0_box)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 5, 1, 1)
        self.label_7 = QtGui.QLabel(self.reg0_box)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 6, 1, 1)
        self.label_8 = QtGui.QLabel(self.reg0_box)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 7, 1, 1)
        self.verticalLayout_11.addWidget(self.reg0_box)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_11.addWidget(self.groupBox)
        self.registers_tab.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_12 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_12)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.reg14 = QtGui.QCheckBox(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg14.setFont(font)
        self.reg14.setObjectName(_fromUtf8("reg14"))
        self.gridLayout_3.addWidget(self.reg14, 2, 3, 1, 1)
        self.reg11 = QtGui.QCheckBox(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg11.setFont(font)
        self.reg11.setObjectName(_fromUtf8("reg11"))
        self.gridLayout_3.addWidget(self.reg11, 2, 6, 1, 1)
        self.write_reg1 = hexSpinbox.HexSpinBox(self.groupBox_12)
        self.write_reg1.setMaximum(255)
        self.write_reg1.setObjectName(_fromUtf8("write_reg1"))
        self.gridLayout_3.addWidget(self.write_reg1, 2, 11, 1, 1)
        self.reg17 = QtGui.QCheckBox(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg17.setFont(font)
        self.reg17.setObjectName(_fromUtf8("reg17"))
        self.gridLayout_3.addWidget(self.reg17, 2, 0, 1, 1)
        self.reg13 = QtGui.QCheckBox(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg13.setFont(font)
        self.reg13.setObjectName(_fromUtf8("reg13"))
        self.gridLayout_3.addWidget(self.reg13, 2, 4, 1, 1)
        self.reg12 = QtGui.QCheckBox(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg12.setFont(font)
        self.reg12.setObjectName(_fromUtf8("reg12"))
        self.gridLayout_3.addWidget(self.reg12, 2, 5, 1, 1)
        self.reg15 = QtGui.QCheckBox(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg15.setFont(font)
        self.reg15.setObjectName(_fromUtf8("reg15"))
        self.gridLayout_3.addWidget(self.reg15, 2, 2, 1, 1)
        self.readbtn_reg1 = QtGui.QPushButton(self.groupBox_12)
        self.readbtn_reg1.setObjectName(_fromUtf8("readbtn_reg1"))
        self.gridLayout_3.addWidget(self.readbtn_reg1, 2, 8, 1, 1)
        self.reg10 = QtGui.QCheckBox(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg10.setFont(font)
        self.reg10.setObjectName(_fromUtf8("reg10"))
        self.gridLayout_3.addWidget(self.reg10, 2, 7, 1, 1)
        self.read_reg1 = hexSpinbox.HexSpinBox(self.groupBox_12)
        self.read_reg1.setEnabled(False)
        self.read_reg1.setMaximum(255)
        self.read_reg1.setObjectName(_fromUtf8("read_reg1"))
        self.gridLayout_3.addWidget(self.read_reg1, 2, 9, 1, 1)
        self.reg16 = QtGui.QCheckBox(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg16.setFont(font)
        self.reg16.setObjectName(_fromUtf8("reg16"))
        self.gridLayout_3.addWidget(self.reg16, 2, 1, 1, 1)
        self.writebtn_reg1 = QtGui.QPushButton(self.groupBox_12)
        self.writebtn_reg1.setObjectName(_fromUtf8("writebtn_reg1"))
        self.gridLayout_3.addWidget(self.writebtn_reg1, 2, 10, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_12)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_12)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 1, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_12)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 1, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_12)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 1, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_12)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 4, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_12)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 1, 5, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_12)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 1, 6, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_12)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 7, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_12)
        self.groupBox_13 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_13)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.reg31 = QtGui.QCheckBox(self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg31.setFont(font)
        self.reg31.setObjectName(_fromUtf8("reg31"))
        self.gridLayout_7.addWidget(self.reg31, 2, 6, 1, 1)
        self.reg30 = QtGui.QCheckBox(self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg30.setFont(font)
        self.reg30.setObjectName(_fromUtf8("reg30"))
        self.gridLayout_7.addWidget(self.reg30, 2, 7, 1, 1)
        self.reg33 = QtGui.QCheckBox(self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg33.setFont(font)
        self.reg33.setObjectName(_fromUtf8("reg33"))
        self.gridLayout_7.addWidget(self.reg33, 2, 4, 1, 1)
        self.reg36 = QtGui.QCheckBox(self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg36.setFont(font)
        self.reg36.setObjectName(_fromUtf8("reg36"))
        self.gridLayout_7.addWidget(self.reg36, 2, 1, 1, 1)
        self.reg32 = QtGui.QCheckBox(self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg32.setFont(font)
        self.reg32.setObjectName(_fromUtf8("reg32"))
        self.gridLayout_7.addWidget(self.reg32, 2, 5, 1, 1)
        self.reg34 = QtGui.QCheckBox(self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg34.setFont(font)
        self.reg34.setObjectName(_fromUtf8("reg34"))
        self.gridLayout_7.addWidget(self.reg34, 2, 3, 1, 1)
        self.reg35 = QtGui.QCheckBox(self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg35.setFont(font)
        self.reg35.setObjectName(_fromUtf8("reg35"))
        self.gridLayout_7.addWidget(self.reg35, 2, 2, 1, 1)
        self.writebtn_reg3 = QtGui.QPushButton(self.groupBox_13)
        self.writebtn_reg3.setObjectName(_fromUtf8("writebtn_reg3"))
        self.gridLayout_7.addWidget(self.writebtn_reg3, 2, 10, 1, 1)
        self.read_reg3 = hexSpinbox.HexSpinBox(self.groupBox_13)
        self.read_reg3.setEnabled(False)
        self.read_reg3.setMaximum(255)
        self.read_reg3.setObjectName(_fromUtf8("read_reg3"))
        self.gridLayout_7.addWidget(self.read_reg3, 2, 9, 1, 1)
        self.write_reg3 = hexSpinbox.HexSpinBox(self.groupBox_13)
        self.write_reg3.setMaximum(255)
        self.write_reg3.setObjectName(_fromUtf8("write_reg3"))
        self.gridLayout_7.addWidget(self.write_reg3, 2, 11, 1, 1)
        self.readbtn_reg3 = QtGui.QPushButton(self.groupBox_13)
        self.readbtn_reg3.setObjectName(_fromUtf8("readbtn_reg3"))
        self.gridLayout_7.addWidget(self.readbtn_reg3, 2, 8, 1, 1)
        self.reg37 = QtGui.QCheckBox(self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg37.setFont(font)
        self.reg37.setObjectName(_fromUtf8("reg37"))
        self.gridLayout_7.addWidget(self.reg37, 2, 0, 1, 1)
        self.label_47 = QtGui.QLabel(self.groupBox_13)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_7.addWidget(self.label_47, 1, 0, 1, 1)
        self.label_45 = QtGui.QLabel(self.groupBox_13)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_7.addWidget(self.label_45, 1, 1, 1, 1)
        self.label_48 = QtGui.QLabel(self.groupBox_13)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_7.addWidget(self.label_48, 1, 2, 1, 1)
        self.label_44 = QtGui.QLabel(self.groupBox_13)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_7.addWidget(self.label_44, 1, 3, 1, 1)
        self.label_41 = QtGui.QLabel(self.groupBox_13)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_7.addWidget(self.label_41, 1, 4, 1, 1)
        self.label_46 = QtGui.QLabel(self.groupBox_13)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_7.addWidget(self.label_46, 1, 5, 1, 1)
        self.label_43 = QtGui.QLabel(self.groupBox_13)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_7.addWidget(self.label_43, 1, 6, 1, 1)
        self.label_42 = QtGui.QLabel(self.groupBox_13)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_7.addWidget(self.label_42, 1, 7, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_13)
        self.registers_tab.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_14 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_14.setEnabled(False)
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_14)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.reg24 = QtGui.QCheckBox(self.groupBox_14)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg24.setFont(font)
        self.reg24.setObjectName(_fromUtf8("reg24"))
        self.gridLayout_6.addWidget(self.reg24, 2, 3, 1, 1)
        self.reg27 = QtGui.QCheckBox(self.groupBox_14)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg27.setFont(font)
        self.reg27.setObjectName(_fromUtf8("reg27"))
        self.gridLayout_6.addWidget(self.reg27, 2, 0, 1, 1)
        self.reg20 = QtGui.QCheckBox(self.groupBox_14)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg20.setFont(font)
        self.reg20.setObjectName(_fromUtf8("reg20"))
        self.gridLayout_6.addWidget(self.reg20, 2, 7, 1, 1)
        self.readbtn_reg2 = QtGui.QPushButton(self.groupBox_14)
        self.readbtn_reg2.setObjectName(_fromUtf8("readbtn_reg2"))
        self.gridLayout_6.addWidget(self.readbtn_reg2, 2, 8, 1, 1)
        self.read_reg2 = hexSpinbox.HexSpinBox(self.groupBox_14)
        self.read_reg2.setEnabled(False)
        self.read_reg2.setMaximum(255)
        self.read_reg2.setObjectName(_fromUtf8("read_reg2"))
        self.gridLayout_6.addWidget(self.read_reg2, 2, 9, 1, 1)
        self.reg26 = QtGui.QCheckBox(self.groupBox_14)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg26.setFont(font)
        self.reg26.setObjectName(_fromUtf8("reg26"))
        self.gridLayout_6.addWidget(self.reg26, 2, 1, 1, 1)
        self.spinBox_11 = hexSpinbox.HexSpinBox(self.groupBox_14)
        self.spinBox_11.setMaximum(255)
        self.spinBox_11.setObjectName(_fromUtf8("spinBox_11"))
        self.gridLayout_6.addWidget(self.spinBox_11, 2, 11, 1, 1)
        self.reg23 = QtGui.QCheckBox(self.groupBox_14)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg23.setFont(font)
        self.reg23.setObjectName(_fromUtf8("reg23"))
        self.gridLayout_6.addWidget(self.reg23, 2, 4, 1, 1)
        self.reg21 = QtGui.QCheckBox(self.groupBox_14)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg21.setFont(font)
        self.reg21.setObjectName(_fromUtf8("reg21"))
        self.gridLayout_6.addWidget(self.reg21, 2, 6, 1, 1)
        self.reg25 = QtGui.QCheckBox(self.groupBox_14)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg25.setFont(font)
        self.reg25.setObjectName(_fromUtf8("reg25"))
        self.gridLayout_6.addWidget(self.reg25, 2, 2, 1, 1)
        self.writebtn_reg2 = QtGui.QPushButton(self.groupBox_14)
        self.writebtn_reg2.setObjectName(_fromUtf8("writebtn_reg2"))
        self.gridLayout_6.addWidget(self.writebtn_reg2, 2, 10, 1, 1)
        self.reg22 = QtGui.QCheckBox(self.groupBox_14)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg22.setFont(font)
        self.reg22.setObjectName(_fromUtf8("reg22"))
        self.gridLayout_6.addWidget(self.reg22, 2, 5, 1, 1)
        self.label_39 = QtGui.QLabel(self.groupBox_14)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_6.addWidget(self.label_39, 1, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.groupBox_14)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_6.addWidget(self.label_37, 1, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.groupBox_14)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_6.addWidget(self.label_40, 1, 2, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox_14)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_6.addWidget(self.label_36, 1, 3, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupBox_14)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_6.addWidget(self.label_33, 1, 4, 1, 1)
        self.label_38 = QtGui.QLabel(self.groupBox_14)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_6.addWidget(self.label_38, 1, 5, 1, 1)
        self.label_35 = QtGui.QLabel(self.groupBox_14)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_6.addWidget(self.label_35, 1, 6, 1, 1)
        self.label_34 = QtGui.QLabel(self.groupBox_14)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_6.addWidget(self.label_34, 1, 7, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_14)
        self.groupBox_18 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_18.setEnabled(False)
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_18)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.reg45 = QtGui.QCheckBox(self.groupBox_18)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg45.setFont(font)
        self.reg45.setObjectName(_fromUtf8("reg45"))
        self.gridLayout_8.addWidget(self.reg45, 2, 2, 1, 1)
        self.reg44 = QtGui.QCheckBox(self.groupBox_18)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg44.setFont(font)
        self.reg44.setObjectName(_fromUtf8("reg44"))
        self.gridLayout_8.addWidget(self.reg44, 2, 3, 1, 1)
        self.writebtn_reg4 = QtGui.QPushButton(self.groupBox_18)
        self.writebtn_reg4.setObjectName(_fromUtf8("writebtn_reg4"))
        self.gridLayout_8.addWidget(self.writebtn_reg4, 2, 10, 1, 1)
        self.reg40 = QtGui.QCheckBox(self.groupBox_18)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg40.setFont(font)
        self.reg40.setObjectName(_fromUtf8("reg40"))
        self.gridLayout_8.addWidget(self.reg40, 2, 7, 1, 1)
        self.reg42 = QtGui.QCheckBox(self.groupBox_18)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg42.setFont(font)
        self.reg42.setObjectName(_fromUtf8("reg42"))
        self.gridLayout_8.addWidget(self.reg42, 2, 5, 1, 1)
        self.reg47 = QtGui.QCheckBox(self.groupBox_18)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg47.setFont(font)
        self.reg47.setObjectName(_fromUtf8("reg47"))
        self.gridLayout_8.addWidget(self.reg47, 2, 0, 1, 1)
        self.reg43 = QtGui.QCheckBox(self.groupBox_18)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg43.setFont(font)
        self.reg43.setObjectName(_fromUtf8("reg43"))
        self.gridLayout_8.addWidget(self.reg43, 2, 4, 1, 1)
        self.read_reg4 = hexSpinbox.HexSpinBox(self.groupBox_18)
        self.read_reg4.setEnabled(False)
        self.read_reg4.setMaximum(255)
        self.read_reg4.setObjectName(_fromUtf8("read_reg4"))
        self.gridLayout_8.addWidget(self.read_reg4, 2, 9, 1, 1)
        self.reg41 = QtGui.QCheckBox(self.groupBox_18)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg41.setFont(font)
        self.reg41.setObjectName(_fromUtf8("reg41"))
        self.gridLayout_8.addWidget(self.reg41, 2, 6, 1, 1)
        self.write_reg4 = hexSpinbox.HexSpinBox(self.groupBox_18)
        self.write_reg4.setMaximum(255)
        self.write_reg4.setObjectName(_fromUtf8("write_reg4"))
        self.gridLayout_8.addWidget(self.write_reg4, 2, 11, 1, 1)
        self.readbtn_reg4 = QtGui.QPushButton(self.groupBox_18)
        self.readbtn_reg4.setObjectName(_fromUtf8("readbtn_reg4"))
        self.gridLayout_8.addWidget(self.readbtn_reg4, 2, 8, 1, 1)
        self.reg46 = QtGui.QCheckBox(self.groupBox_18)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reg46.setFont(font)
        self.reg46.setObjectName(_fromUtf8("reg46"))
        self.gridLayout_8.addWidget(self.reg46, 2, 1, 1, 1)
        self.label_55 = QtGui.QLabel(self.groupBox_18)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_8.addWidget(self.label_55, 1, 0, 1, 1)
        self.label_53 = QtGui.QLabel(self.groupBox_18)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_8.addWidget(self.label_53, 1, 1, 1, 1)
        self.label_56 = QtGui.QLabel(self.groupBox_18)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_8.addWidget(self.label_56, 1, 2, 1, 1)
        self.label_52 = QtGui.QLabel(self.groupBox_18)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_8.addWidget(self.label_52, 1, 3, 1, 1)
        self.label_49 = QtGui.QLabel(self.groupBox_18)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_8.addWidget(self.label_49, 1, 4, 1, 1)
        self.label_54 = QtGui.QLabel(self.groupBox_18)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_8.addWidget(self.label_54, 1, 5, 1, 1)
        self.label_51 = QtGui.QLabel(self.groupBox_18)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_8.addWidget(self.label_51, 1, 6, 1, 1)
        self.label_50 = QtGui.QLabel(self.groupBox_18)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_8.addWidget(self.label_50, 1, 7, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_18)
        self.registers_tab.addTab(self.tab_3, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.groupBox_17 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_17.setEnabled(False)
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_17)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_61 = QtGui.QLabel(self.groupBox_17)
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_9.addWidget(self.label_61, 1, 1, 1, 1)
        self.label_59 = QtGui.QLabel(self.groupBox_17)
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_9.addWidget(self.label_59, 1, 6, 1, 1)
        self.label_60 = QtGui.QLabel(self.groupBox_17)
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_9.addWidget(self.label_60, 1, 3, 1, 1)
        self.label_62 = QtGui.QLabel(self.groupBox_17)
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_9.addWidget(self.label_62, 1, 5, 1, 1)
        self.label_57 = QtGui.QLabel(self.groupBox_17)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_9.addWidget(self.label_57, 1, 4, 1, 1)
        self.label_64 = QtGui.QLabel(self.groupBox_17)
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_9.addWidget(self.label_64, 1, 2, 1, 1)
        self.checkBox_49 = QtGui.QCheckBox(self.groupBox_17)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_49.setFont(font)
        self.checkBox_49.setObjectName(_fromUtf8("checkBox_49"))
        self.gridLayout_9.addWidget(self.checkBox_49, 3, 0, 1, 1)
        self.pushButton_13 = QtGui.QPushButton(self.groupBox_17)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.gridLayout_9.addWidget(self.pushButton_13, 3, 8, 1, 1)
        self.spinBox_14 = hexSpinbox.HexSpinBox(self.groupBox_17)
        self.spinBox_14.setMaximum(255)
        self.spinBox_14.setObjectName(_fromUtf8("spinBox_14"))
        self.gridLayout_9.addWidget(self.spinBox_14, 3, 11, 1, 1)
        self.checkBox_51 = QtGui.QCheckBox(self.groupBox_17)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_51.setFont(font)
        self.checkBox_51.setObjectName(_fromUtf8("checkBox_51"))
        self.gridLayout_9.addWidget(self.checkBox_51, 3, 2, 1, 1)
        self.pushButton_14 = QtGui.QPushButton(self.groupBox_17)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.gridLayout_9.addWidget(self.pushButton_14, 3, 10, 1, 1)
        self.checkBox_52 = QtGui.QCheckBox(self.groupBox_17)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_52.setFont(font)
        self.checkBox_52.setObjectName(_fromUtf8("checkBox_52"))
        self.gridLayout_9.addWidget(self.checkBox_52, 3, 3, 1, 1)
        self.label_63 = QtGui.QLabel(self.groupBox_17)
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_9.addWidget(self.label_63, 1, 0, 1, 1)
        self.checkBox_54 = QtGui.QCheckBox(self.groupBox_17)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_54.setFont(font)
        self.checkBox_54.setObjectName(_fromUtf8("checkBox_54"))
        self.gridLayout_9.addWidget(self.checkBox_54, 3, 5, 1, 1)
        self.checkBox_50 = QtGui.QCheckBox(self.groupBox_17)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_50.setFont(font)
        self.checkBox_50.setObjectName(_fromUtf8("checkBox_50"))
        self.gridLayout_9.addWidget(self.checkBox_50, 3, 1, 1, 1)
        self.spinBox_7 = hexSpinbox.HexSpinBox(self.groupBox_17)
        self.spinBox_7.setEnabled(False)
        self.spinBox_7.setMaximum(255)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.gridLayout_9.addWidget(self.spinBox_7, 3, 9, 1, 1)
        self.checkBox_53 = QtGui.QCheckBox(self.groupBox_17)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_53.setFont(font)
        self.checkBox_53.setObjectName(_fromUtf8("checkBox_53"))
        self.gridLayout_9.addWidget(self.checkBox_53, 3, 4, 1, 1)
        self.checkBox_55 = QtGui.QCheckBox(self.groupBox_17)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_55.setFont(font)
        self.checkBox_55.setObjectName(_fromUtf8("checkBox_55"))
        self.gridLayout_9.addWidget(self.checkBox_55, 3, 6, 1, 1)
        self.checkBox_56 = QtGui.QCheckBox(self.groupBox_17)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_56.setFont(font)
        self.checkBox_56.setObjectName(_fromUtf8("checkBox_56"))
        self.gridLayout_9.addWidget(self.checkBox_56, 3, 7, 1, 1)
        self.label_58 = QtGui.QLabel(self.groupBox_17)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_9.addWidget(self.label_58, 1, 7, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_17)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_12.addWidget(self.groupBox_4)
        self.registers_tab.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.tab_7)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.groupBox_16 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_16.setEnabled(False)
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_16)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.pushButton_12 = QtGui.QPushButton(self.groupBox_16)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.gridLayout_10.addWidget(self.pushButton_12, 2, 10, 1, 1)
        self.spinBox_6 = hexSpinbox.HexSpinBox(self.groupBox_16)
        self.spinBox_6.setEnabled(False)
        self.spinBox_6.setMaximum(255)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.gridLayout_10.addWidget(self.spinBox_6, 2, 9, 1, 1)
        self.spinBox_15 = hexSpinbox.HexSpinBox(self.groupBox_16)
        self.spinBox_15.setMaximum(255)
        self.spinBox_15.setObjectName(_fromUtf8("spinBox_15"))
        self.gridLayout_10.addWidget(self.spinBox_15, 2, 11, 1, 1)
        self.checkBox_46 = QtGui.QCheckBox(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_46.setFont(font)
        self.checkBox_46.setObjectName(_fromUtf8("checkBox_46"))
        self.gridLayout_10.addWidget(self.checkBox_46, 2, 5, 1, 1)
        self.checkBox_44 = QtGui.QCheckBox(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_44.setFont(font)
        self.checkBox_44.setObjectName(_fromUtf8("checkBox_44"))
        self.gridLayout_10.addWidget(self.checkBox_44, 2, 3, 1, 1)
        self.pushButton_11 = QtGui.QPushButton(self.groupBox_16)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout_10.addWidget(self.pushButton_11, 2, 8, 1, 1)
        self.checkBox_42 = QtGui.QCheckBox(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_42.setFont(font)
        self.checkBox_42.setObjectName(_fromUtf8("checkBox_42"))
        self.gridLayout_10.addWidget(self.checkBox_42, 2, 1, 1, 1)
        self.checkBox_48 = QtGui.QCheckBox(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_48.setFont(font)
        self.checkBox_48.setObjectName(_fromUtf8("checkBox_48"))
        self.gridLayout_10.addWidget(self.checkBox_48, 2, 7, 1, 1)
        self.checkBox_45 = QtGui.QCheckBox(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_45.setFont(font)
        self.checkBox_45.setObjectName(_fromUtf8("checkBox_45"))
        self.gridLayout_10.addWidget(self.checkBox_45, 2, 4, 1, 1)
        self.checkBox_41 = QtGui.QCheckBox(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_41.setFont(font)
        self.checkBox_41.setObjectName(_fromUtf8("checkBox_41"))
        self.gridLayout_10.addWidget(self.checkBox_41, 2, 0, 1, 1)
        self.checkBox_47 = QtGui.QCheckBox(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_47.setFont(font)
        self.checkBox_47.setObjectName(_fromUtf8("checkBox_47"))
        self.gridLayout_10.addWidget(self.checkBox_47, 2, 6, 1, 1)
        self.checkBox_43 = QtGui.QCheckBox(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_43.setFont(font)
        self.checkBox_43.setObjectName(_fromUtf8("checkBox_43"))
        self.gridLayout_10.addWidget(self.checkBox_43, 2, 2, 1, 1)
        self.label_71 = QtGui.QLabel(self.groupBox_16)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout_10.addWidget(self.label_71, 1, 0, 1, 1)
        self.label_69 = QtGui.QLabel(self.groupBox_16)
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout_10.addWidget(self.label_69, 1, 1, 1, 1)
        self.label_72 = QtGui.QLabel(self.groupBox_16)
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout_10.addWidget(self.label_72, 1, 2, 1, 1)
        self.label_68 = QtGui.QLabel(self.groupBox_16)
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout_10.addWidget(self.label_68, 1, 3, 1, 1)
        self.label_65 = QtGui.QLabel(self.groupBox_16)
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_10.addWidget(self.label_65, 1, 4, 1, 1)
        self.label_70 = QtGui.QLabel(self.groupBox_16)
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_10.addWidget(self.label_70, 1, 5, 1, 1)
        self.label_67 = QtGui.QLabel(self.groupBox_16)
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_10.addWidget(self.label_67, 1, 6, 1, 1)
        self.label_66 = QtGui.QLabel(self.groupBox_16)
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_10.addWidget(self.label_66, 1, 7, 1, 1)
        self.verticalLayout_13.addWidget(self.groupBox_16)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_13.addWidget(self.groupBox_3)
        self.registers_tab.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.tab_8)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.groupBox_15 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_15.setEnabled(False)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_15)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.checkBox_33 = QtGui.QCheckBox(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_33.setFont(font)
        self.checkBox_33.setObjectName(_fromUtf8("checkBox_33"))
        self.gridLayout_11.addWidget(self.checkBox_33, 2, 0, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_15)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_11.addWidget(self.pushButton_9, 2, 8, 1, 1)
        self.spinBox_16 = hexSpinbox.HexSpinBox(self.groupBox_15)
        self.spinBox_16.setMaximum(255)
        self.spinBox_16.setObjectName(_fromUtf8("spinBox_16"))
        self.gridLayout_11.addWidget(self.spinBox_16, 2, 11, 1, 1)
        self.spinBox_5 = hexSpinbox.HexSpinBox(self.groupBox_15)
        self.spinBox_5.setEnabled(False)
        self.spinBox_5.setMaximum(255)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.gridLayout_11.addWidget(self.spinBox_5, 2, 9, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_15)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_11.addWidget(self.pushButton_10, 2, 10, 1, 1)
        self.checkBox_35 = QtGui.QCheckBox(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_35.setFont(font)
        self.checkBox_35.setObjectName(_fromUtf8("checkBox_35"))
        self.gridLayout_11.addWidget(self.checkBox_35, 2, 2, 1, 1)
        self.checkBox_39 = QtGui.QCheckBox(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_39.setFont(font)
        self.checkBox_39.setObjectName(_fromUtf8("checkBox_39"))
        self.gridLayout_11.addWidget(self.checkBox_39, 2, 6, 1, 1)
        self.checkBox_37 = QtGui.QCheckBox(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_37.setFont(font)
        self.checkBox_37.setObjectName(_fromUtf8("checkBox_37"))
        self.gridLayout_11.addWidget(self.checkBox_37, 2, 4, 1, 1)
        self.checkBox_34 = QtGui.QCheckBox(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_34.setFont(font)
        self.checkBox_34.setObjectName(_fromUtf8("checkBox_34"))
        self.gridLayout_11.addWidget(self.checkBox_34, 2, 1, 1, 1)
        self.checkBox_36 = QtGui.QCheckBox(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_36.setFont(font)
        self.checkBox_36.setObjectName(_fromUtf8("checkBox_36"))
        self.gridLayout_11.addWidget(self.checkBox_36, 2, 3, 1, 1)
        self.checkBox_38 = QtGui.QCheckBox(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_38.setFont(font)
        self.checkBox_38.setObjectName(_fromUtf8("checkBox_38"))
        self.gridLayout_11.addWidget(self.checkBox_38, 2, 5, 1, 1)
        self.checkBox_40 = QtGui.QCheckBox(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_40.setFont(font)
        self.checkBox_40.setObjectName(_fromUtf8("checkBox_40"))
        self.gridLayout_11.addWidget(self.checkBox_40, 2, 7, 1, 1)
        self.label_79 = QtGui.QLabel(self.groupBox_15)
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.gridLayout_11.addWidget(self.label_79, 1, 0, 1, 1)
        self.label_77 = QtGui.QLabel(self.groupBox_15)
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.gridLayout_11.addWidget(self.label_77, 1, 1, 1, 1)
        self.label_80 = QtGui.QLabel(self.groupBox_15)
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.gridLayout_11.addWidget(self.label_80, 1, 2, 1, 1)
        self.label_76 = QtGui.QLabel(self.groupBox_15)
        self.label_76.setAlignment(QtCore.Qt.AlignCenter)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout_11.addWidget(self.label_76, 1, 3, 1, 1)
        self.label_73 = QtGui.QLabel(self.groupBox_15)
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.gridLayout_11.addWidget(self.label_73, 1, 4, 1, 1)
        self.label_78 = QtGui.QLabel(self.groupBox_15)
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.gridLayout_11.addWidget(self.label_78, 1, 5, 1, 1)
        self.label_75 = QtGui.QLabel(self.groupBox_15)
        self.label_75.setAlignment(QtCore.Qt.AlignCenter)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout_11.addWidget(self.label_75, 1, 6, 1, 1)
        self.label_74 = QtGui.QLabel(self.groupBox_15)
        self.label_74.setAlignment(QtCore.Qt.AlignCenter)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.gridLayout_11.addWidget(self.label_74, 1, 7, 1, 1)
        self.verticalLayout_14.addWidget(self.groupBox_15)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_14.addWidget(self.groupBox_2)
        self.registers_tab.addTab(self.tab_8, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.registers_tab)
        self.gridLayout.addWidget(self.regixters_box, 3, 0, 1, 1)

        self.retranslateUi(Form)
        self.portList.setCurrentIndex(-1)
        self.registers_tab.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "TinyI2C", None))
        self.conport_box.setTitle(_translate("Form", "COM port", None))
        self.getPortBtn.setText(_translate("Form", "Search", None))
        self.log_box.setTitle(_translate("Form", "Log message", None))
        self.log_text.setPlainText(_translate("Form", "This is \n"
"a\n"
"log message\n"
"window", None))
        self.i2c_box.setTitle(_translate("Form", "Interfaces", None))
        self.i2c1_box.setTitle(_translate("Form", "I2C0", None))
        self.readbtn_CH1.setText(_translate("Form", "Read", None))
        self.writebtn_CH1.setText(_translate("Form", "Write", None))
        self.i2c2_box.setTitle(_translate("Form", "I2C1", None))
        self.readbtn_CH2.setText(_translate("Form", "Read", None))
        self.writebtn_CH2.setText(_translate("Form", "Write", None))
        self.i2c3_box.setTitle(_translate("Form", "I2C2", None))
        self.readbtn_CH3.setText(_translate("Form", "Read", None))
        self.writebtn_CH3.setText(_translate("Form", "Write", None))
        self.i2c4_box.setTitle(_translate("Form", "I2C3", None))
        self.readbtn_CH4.setText(_translate("Form", "Read", None))
        self.writebtn_CH4.setText(_translate("Form", "Write", None))
        self.spi_box.setTitle(_translate("Form", "SPI", None))
        self.readbtn_SPI.setText(_translate("Form", "Read", None))
        self.writebtn_SPI.setText(_translate("Form", "Write", None))
        self.regixters_box.setTitle(_translate("Form", "Registers", None))
        self.reg0_box.setTitle(_translate("Form", "Register 0", None))
        self.reg07.setText(_translate("Form", "0", None))
        self.reg06.setText(_translate("Form", "0", None))
        self.reg05.setText(_translate("Form", "0", None))
        self.reg04.setText(_translate("Form", "0", None))
        self.reg03.setText(_translate("Form", "0", None))
        self.reg02.setText(_translate("Form", "0", None))
        self.reg01.setText(_translate("Form", "0", None))
        self.reg00.setText(_translate("Form", "0", None))
        self.readbtn_reg0.setText(_translate("Form", "Read", None))
        self.writebtn_reg0.setText(_translate("Form", "Write", None))
        self.label.setText(_translate("Form", "[7]", None))
        self.label_2.setText(_translate("Form", "[6]", None))
        self.label_3.setText(_translate("Form", "[5]", None))
        self.label_4.setText(_translate("Form", "[4]", None))
        self.label_5.setText(_translate("Form", "[3]", None))
        self.label_6.setText(_translate("Form", "[2]", None))
        self.label_7.setText(_translate("Form", "[1]", None))
        self.label_8.setText(_translate("Form", "[0]", None))
        self.registers_tab.setTabText(self.registers_tab.indexOf(self.tab), _translate("Form", "CHIP_ID", None))
        self.groupBox_12.setTitle(_translate("Form", "STATUS", None))
        self.reg14.setText(_translate("Form", "0", None))
        self.reg11.setText(_translate("Form", "0", None))
        self.reg17.setText(_translate("Form", "0", None))
        self.reg13.setText(_translate("Form", "0", None))
        self.reg12.setText(_translate("Form", "0", None))
        self.reg15.setText(_translate("Form", "0", None))
        self.readbtn_reg1.setText(_translate("Form", "Read", None))
        self.reg10.setText(_translate("Form", "0", None))
        self.reg16.setText(_translate("Form", "0", None))
        self.writebtn_reg1.setText(_translate("Form", "Write", None))
        self.label_15.setText(_translate("Form", "[7]", None))
        self.label_13.setText(_translate("Form", "[6]", None))
        self.label_16.setText(_translate("Form", "[5]", None))
        self.label_12.setText(_translate("Form", "[4]", None))
        self.label_9.setText(_translate("Form", "[3]", None))
        self.label_14.setText(_translate("Form", "[2]", None))
        self.label_11.setText(_translate("Form", "[1]", None))
        self.label_10.setText(_translate("Form", "[0]", None))
        self.groupBox_13.setTitle(_translate("Form", "CONFIG", None))
        self.reg31.setText(_translate("Form", "0", None))
        self.reg30.setText(_translate("Form", "0", None))
        self.reg33.setText(_translate("Form", "0", None))
        self.reg36.setText(_translate("Form", "0", None))
        self.reg32.setText(_translate("Form", "0", None))
        self.reg34.setText(_translate("Form", "0", None))
        self.reg35.setText(_translate("Form", "0", None))
        self.writebtn_reg3.setText(_translate("Form", "Write", None))
        self.readbtn_reg3.setText(_translate("Form", "Read", None))
        self.reg37.setText(_translate("Form", "0", None))
        self.label_47.setText(_translate("Form", "[7]", None))
        self.label_45.setText(_translate("Form", "[6]", None))
        self.label_48.setText(_translate("Form", "[5]", None))
        self.label_44.setText(_translate("Form", "[4]", None))
        self.label_41.setText(_translate("Form", "[3]", None))
        self.label_46.setText(_translate("Form", "[2]", None))
        self.label_43.setText(_translate("Form", "[1]", None))
        self.label_42.setText(_translate("Form", "[0]", None))
        self.registers_tab.setTabText(self.registers_tab.indexOf(self.tab_2), _translate("Form", "GPIO0", None))
        self.groupBox_14.setTitle(_translate("Form", "STATUS", None))
        self.reg24.setText(_translate("Form", "0", None))
        self.reg27.setText(_translate("Form", "0", None))
        self.reg20.setText(_translate("Form", "0", None))
        self.readbtn_reg2.setText(_translate("Form", "Read", None))
        self.reg26.setText(_translate("Form", "0", None))
        self.reg23.setText(_translate("Form", "0", None))
        self.reg21.setText(_translate("Form", "0", None))
        self.reg25.setText(_translate("Form", "0", None))
        self.writebtn_reg2.setText(_translate("Form", "Write", None))
        self.reg22.setText(_translate("Form", "0", None))
        self.label_39.setText(_translate("Form", "[7]", None))
        self.label_37.setText(_translate("Form", "[6]", None))
        self.label_40.setText(_translate("Form", "[5]", None))
        self.label_36.setText(_translate("Form", "[4]", None))
        self.label_33.setText(_translate("Form", "[3]", None))
        self.label_38.setText(_translate("Form", "[2]", None))
        self.label_35.setText(_translate("Form", "[1]", None))
        self.label_34.setText(_translate("Form", "[0]", None))
        self.groupBox_18.setTitle(_translate("Form", "CONFIG", None))
        self.reg45.setText(_translate("Form", "0", None))
        self.reg44.setText(_translate("Form", "0", None))
        self.writebtn_reg4.setText(_translate("Form", "Write", None))
        self.reg40.setText(_translate("Form", "0", None))
        self.reg42.setText(_translate("Form", "0", None))
        self.reg47.setText(_translate("Form", "0", None))
        self.reg43.setText(_translate("Form", "0", None))
        self.reg41.setText(_translate("Form", "0", None))
        self.readbtn_reg4.setText(_translate("Form", "Read", None))
        self.reg46.setText(_translate("Form", "0", None))
        self.label_55.setText(_translate("Form", "[7]", None))
        self.label_53.setText(_translate("Form", "[6]", None))
        self.label_56.setText(_translate("Form", "[5]", None))
        self.label_52.setText(_translate("Form", "[4]", None))
        self.label_49.setText(_translate("Form", "[3]", None))
        self.label_54.setText(_translate("Form", "[2]", None))
        self.label_51.setText(_translate("Form", "[1]", None))
        self.label_50.setText(_translate("Form", "[0]", None))
        self.registers_tab.setTabText(self.registers_tab.indexOf(self.tab_3), _translate("Form", "GPIO1", None))
        self.groupBox_17.setTitle(_translate("Form", "Register 5", None))
        self.label_61.setText(_translate("Form", "[6]", None))
        self.label_59.setText(_translate("Form", "[1]", None))
        self.label_60.setText(_translate("Form", "[4]", None))
        self.label_62.setText(_translate("Form", "[2]", None))
        self.label_57.setText(_translate("Form", "[3]", None))
        self.label_64.setText(_translate("Form", "[5]", None))
        self.checkBox_49.setText(_translate("Form", "0", None))
        self.pushButton_13.setText(_translate("Form", "Read", None))
        self.checkBox_51.setText(_translate("Form", "0", None))
        self.pushButton_14.setText(_translate("Form", "Write", None))
        self.checkBox_52.setText(_translate("Form", "0", None))
        self.label_63.setText(_translate("Form", "[7]", None))
        self.checkBox_54.setText(_translate("Form", "0", None))
        self.checkBox_50.setText(_translate("Form", "0", None))
        self.checkBox_53.setText(_translate("Form", "0", None))
        self.checkBox_55.setText(_translate("Form", "0", None))
        self.checkBox_56.setText(_translate("Form", "0", None))
        self.label_58.setText(_translate("Form", "[0]", None))
        self.registers_tab.setTabText(self.registers_tab.indexOf(self.tab_6), _translate("Form", "Unused5", None))
        self.groupBox_16.setTitle(_translate("Form", "Register 6", None))
        self.pushButton_12.setText(_translate("Form", "Write", None))
        self.checkBox_46.setText(_translate("Form", "0", None))
        self.checkBox_44.setText(_translate("Form", "0", None))
        self.pushButton_11.setText(_translate("Form", "Read", None))
        self.checkBox_42.setText(_translate("Form", "0", None))
        self.checkBox_48.setText(_translate("Form", "0", None))
        self.checkBox_45.setText(_translate("Form", "0", None))
        self.checkBox_41.setText(_translate("Form", "0", None))
        self.checkBox_47.setText(_translate("Form", "0", None))
        self.checkBox_43.setText(_translate("Form", "0", None))
        self.label_71.setText(_translate("Form", "[7]", None))
        self.label_69.setText(_translate("Form", "[6]", None))
        self.label_72.setText(_translate("Form", "[5]", None))
        self.label_68.setText(_translate("Form", "[4]", None))
        self.label_65.setText(_translate("Form", "[3]", None))
        self.label_70.setText(_translate("Form", "[2]", None))
        self.label_67.setText(_translate("Form", "[1]", None))
        self.label_66.setText(_translate("Form", "[0]", None))
        self.registers_tab.setTabText(self.registers_tab.indexOf(self.tab_7), _translate("Form", "Unused6", None))
        self.groupBox_15.setTitle(_translate("Form", "Register 7", None))
        self.checkBox_33.setText(_translate("Form", "0", None))
        self.pushButton_9.setText(_translate("Form", "Read", None))
        self.pushButton_10.setText(_translate("Form", "Write", None))
        self.checkBox_35.setText(_translate("Form", "0", None))
        self.checkBox_39.setText(_translate("Form", "0", None))
        self.checkBox_37.setText(_translate("Form", "0", None))
        self.checkBox_34.setText(_translate("Form", "0", None))
        self.checkBox_36.setText(_translate("Form", "0", None))
        self.checkBox_38.setText(_translate("Form", "0", None))
        self.checkBox_40.setText(_translate("Form", "0", None))
        self.label_79.setText(_translate("Form", "[7]", None))
        self.label_77.setText(_translate("Form", "[6]", None))
        self.label_80.setText(_translate("Form", "[5]", None))
        self.label_76.setText(_translate("Form", "[4]", None))
        self.label_73.setText(_translate("Form", "[3]", None))
        self.label_78.setText(_translate("Form", "[2]", None))
        self.label_75.setText(_translate("Form", "[1]", None))
        self.label_74.setText(_translate("Form", "[0]", None))
        self.registers_tab.setTabText(self.registers_tab.indexOf(self.tab_8), _translate("Form", "Unused7", None))

