# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tinyI2C.ui'
#
# Created: Fri Jan 16 17:11:16 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import hexSpinbox

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(662, 630)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.conport_box = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.conport_box.setFont(font)
        self.conport_box.setFlat(False)
        self.conport_box.setCheckable(False)
        self.conport_box.setObjectName(_fromUtf8("conport_box"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.conport_box)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.getPortBtn = QtGui.QPushButton(self.conport_box)
        self.getPortBtn.setObjectName(_fromUtf8("getPortBtn"))
        self.horizontalLayout.addWidget(self.getPortBtn)
        self.portList = QtGui.QComboBox(self.conport_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.portList.setFont(font)
        self.portList.setObjectName(_fromUtf8("portList"))
        self.horizontalLayout.addWidget(self.portList)
        self.gridLayout.addWidget(self.conport_box, 0, 0, 1, 1)
        self.log_box = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.log_box.setFont(font)
        self.log_box.setObjectName(_fromUtf8("log_box"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.log_box)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.log_text = QtGui.QPlainTextEdit(self.log_box)
        self.log_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.log_text.setObjectName(_fromUtf8("log_text"))
        self.log_text.setReadOnly(True)
        self.verticalLayout_9.addWidget(self.log_text)
        self.gridLayout.addWidget(self.log_box, 4, 0, 1, 1)
        self.i2c_box = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i2c_box.setFont(font)
        self.i2c_box.setObjectName(_fromUtf8("i2c_box"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.i2c_box)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.i2c1_box = QtGui.QGroupBox(self.i2c_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i2c1_box.setFont(font)
        self.i2c1_box.setObjectName(_fromUtf8("i2c1_box"))
        self.verticalLayout = QtGui.QVBoxLayout(self.i2c1_box)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.base_CH1 = hexSpinbox.HexSpinBox(self.i2c1_box)
        self.base_CH1.setSuffix(_fromUtf8(""))
        self.base_CH1.setPrefix(_fromUtf8(""))
        self.base_CH1.setMaximum(255)
        self.base_CH1.setProperty("value", 208)
        self.base_CH1.setObjectName(_fromUtf8("base_CH1"))
        self.verticalLayout.addWidget(self.base_CH1)
        self.reg_CH1 = hexSpinbox.HexSpinBox(self.i2c1_box)
        self.reg_CH1.setSuffix(_fromUtf8(""))
        self.reg_CH1.setPrefix(_fromUtf8(""))
        self.reg_CH1.setMaximum(255)
        self.reg_CH1.setObjectName(_fromUtf8("reg_CH1"))
        self.verticalLayout.addWidget(self.reg_CH1)
        self.readbtn_CH1 = QtGui.QPushButton(self.i2c1_box)
        self.readbtn_CH1.setObjectName(_fromUtf8("readbtn_CH1"))
        self.verticalLayout.addWidget(self.readbtn_CH1)
        self.read_CH1 = hexSpinbox.HexSpinBox(self.i2c1_box)
        self.read_CH1.setEnabled(False)
        self.read_CH1.setSuffix(_fromUtf8(""))
        self.read_CH1.setPrefix(_fromUtf8(""))
        self.read_CH1.setMaximum(255)
        self.read_CH1.setObjectName(_fromUtf8("read_CH1"))
        self.verticalLayout.addWidget(self.read_CH1)
        self.writebtn_CH1 = QtGui.QPushButton(self.i2c1_box)
        self.writebtn_CH1.setObjectName(_fromUtf8("writebtn_CH1"))
        self.verticalLayout.addWidget(self.writebtn_CH1)
        self.write_CH1 = hexSpinbox.HexSpinBox(self.i2c1_box)
        self.write_CH1.setSuffix(_fromUtf8(""))
        self.write_CH1.setPrefix(_fromUtf8(""))
        self.write_CH1.setMaximum(255)
        self.write_CH1.setObjectName(_fromUtf8("write_CH1"))
        self.verticalLayout.addWidget(self.write_CH1)
        self.horizontalLayout_6.addWidget(self.i2c1_box)
        self.i2c2_box = QtGui.QGroupBox(self.i2c_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i2c2_box.setFont(font)
        self.i2c2_box.setObjectName(_fromUtf8("i2c2_box"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.i2c2_box)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.base_CH2 = hexSpinbox.HexSpinBox(self.i2c2_box)
        self.base_CH2.setSuffix(_fromUtf8(""))
        self.base_CH2.setPrefix(_fromUtf8(""))
        self.base_CH2.setMaximum(255)
        self.base_CH2.setProperty("value", 208)
        self.base_CH2.setObjectName(_fromUtf8("base_CH2"))
        self.verticalLayout_5.addWidget(self.base_CH2)
        self.reg_CH2 = hexSpinbox.HexSpinBox(self.i2c2_box)
        self.reg_CH2.setSuffix(_fromUtf8(""))
        self.reg_CH2.setPrefix(_fromUtf8(""))
        self.reg_CH2.setMaximum(255)
        self.reg_CH2.setObjectName(_fromUtf8("reg_CH2"))
        self.verticalLayout_5.addWidget(self.reg_CH2)
        self.readbtn_CH2 = QtGui.QPushButton(self.i2c2_box)
        self.readbtn_CH2.setObjectName(_fromUtf8("readbtn_CH2"))
        self.verticalLayout_5.addWidget(self.readbtn_CH2)
        self.read_CH2 = hexSpinbox.HexSpinBox(self.i2c2_box)
        self.read_CH2.setEnabled(False)
        self.read_CH2.setSuffix(_fromUtf8(""))
        self.read_CH2.setPrefix(_fromUtf8(""))
        self.read_CH2.setMaximum(255)
        self.read_CH2.setObjectName(_fromUtf8("read_CH2"))
        self.verticalLayout_5.addWidget(self.read_CH2)
        self.writebtn_CH2 = QtGui.QPushButton(self.i2c2_box)
        self.writebtn_CH2.setObjectName(_fromUtf8("writebtn_CH2"))
        self.verticalLayout_5.addWidget(self.writebtn_CH2)
        self.write_CH2 = hexSpinbox.HexSpinBox(self.i2c2_box)
        self.write_CH2.setSuffix(_fromUtf8(""))
        self.write_CH2.setPrefix(_fromUtf8(""))
        self.write_CH2.setMaximum(255)
        self.write_CH2.setObjectName(_fromUtf8("write_CH2"))
        self.verticalLayout_5.addWidget(self.write_CH2)
        self.horizontalLayout_6.addWidget(self.i2c2_box)
        self.i2c3_box = QtGui.QGroupBox(self.i2c_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i2c3_box.setFont(font)
        self.i2c3_box.setObjectName(_fromUtf8("i2c3_box"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.i2c3_box)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.base_CH3 = hexSpinbox.HexSpinBox(self.i2c3_box)
        self.base_CH3.setSuffix(_fromUtf8(""))
        self.base_CH3.setPrefix(_fromUtf8(""))
        self.base_CH3.setMaximum(255)
        self.base_CH3.setProperty("value", 208)
        self.base_CH3.setObjectName(_fromUtf8("base_CH3"))
        self.verticalLayout_6.addWidget(self.base_CH3)
        self.reg_CH3 = hexSpinbox.HexSpinBox(self.i2c3_box)
        self.reg_CH3.setSuffix(_fromUtf8(""))
        self.reg_CH3.setPrefix(_fromUtf8(""))
        self.reg_CH3.setMaximum(255)
        self.reg_CH3.setObjectName(_fromUtf8("reg_CH3"))
        self.verticalLayout_6.addWidget(self.reg_CH3)
        self.readbtn_CH3 = QtGui.QPushButton(self.i2c3_box)
        self.readbtn_CH3.setObjectName(_fromUtf8("readbtn_CH3"))
        self.verticalLayout_6.addWidget(self.readbtn_CH3)
        self.read_CH3 = hexSpinbox.HexSpinBox(self.i2c3_box)
        self.read_CH3.setEnabled(False)
        self.read_CH3.setSuffix(_fromUtf8(""))
        self.read_CH3.setPrefix(_fromUtf8(""))
        self.read_CH3.setMaximum(255)
        self.read_CH3.setObjectName(_fromUtf8("read_CH3"))
        self.verticalLayout_6.addWidget(self.read_CH3)
        self.writebtn_CH3 = QtGui.QPushButton(self.i2c3_box)
        self.writebtn_CH3.setObjectName(_fromUtf8("writebtn_CH3"))
        self.verticalLayout_6.addWidget(self.writebtn_CH3)
        self.write_CH3 = hexSpinbox.HexSpinBox(self.i2c3_box)
        self.write_CH3.setSuffix(_fromUtf8(""))
        self.write_CH3.setPrefix(_fromUtf8(""))
        self.write_CH3.setMaximum(255)
        self.write_CH3.setObjectName(_fromUtf8("write_CH3"))
        self.verticalLayout_6.addWidget(self.write_CH3)
        self.horizontalLayout_6.addWidget(self.i2c3_box)
        self.i2c4_box = QtGui.QGroupBox(self.i2c_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i2c4_box.setFont(font)
        self.i2c4_box.setObjectName(_fromUtf8("i2c4_box"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.i2c4_box)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.base_CH4 = hexSpinbox.HexSpinBox(self.i2c4_box)
        self.base_CH4.setSuffix(_fromUtf8(""))
        self.base_CH4.setPrefix(_fromUtf8(""))
        self.base_CH4.setMaximum(255)
        self.base_CH4.setProperty("value", 208)
        self.base_CH4.setObjectName(_fromUtf8("base_CH4"))
        self.verticalLayout_7.addWidget(self.base_CH4)
        self.reg_CH4 = hexSpinbox.HexSpinBox(self.i2c4_box)
        self.reg_CH4.setSuffix(_fromUtf8(""))
        self.reg_CH4.setPrefix(_fromUtf8(""))
        self.reg_CH4.setMaximum(255)
        self.reg_CH4.setObjectName(_fromUtf8("reg_CH4"))
        self.verticalLayout_7.addWidget(self.reg_CH4)
        self.readbtn_CH4 = QtGui.QPushButton(self.i2c4_box)
        self.readbtn_CH4.setObjectName(_fromUtf8("readbtn_CH4"))
        self.verticalLayout_7.addWidget(self.readbtn_CH4)
        self.read_CH4 = hexSpinbox.HexSpinBox(self.i2c4_box)
        self.read_CH4.setEnabled(False)
        self.read_CH4.setSuffix(_fromUtf8(""))
        self.read_CH4.setPrefix(_fromUtf8(""))
        self.read_CH4.setMaximum(255)
        self.read_CH4.setObjectName(_fromUtf8("read_CH4"))
        self.verticalLayout_7.addWidget(self.read_CH4)
        self.writebtn_CH4 = QtGui.QPushButton(self.i2c4_box)
        self.writebtn_CH4.setObjectName(_fromUtf8("writebtn_CH4"))
        self.verticalLayout_7.addWidget(self.writebtn_CH4)
        self.write_CH4 = hexSpinbox.HexSpinBox(self.i2c4_box)
        self.write_CH4.setSuffix(_fromUtf8(""))
        self.write_CH4.setPrefix(_fromUtf8(""))
        self.write_CH4.setMaximum(255)
        self.write_CH4.setObjectName(_fromUtf8("write_CH4"))
        self.verticalLayout_7.addWidget(self.write_CH4)
        self.horizontalLayout_6.addWidget(self.i2c4_box)
        self.spi_box = QtGui.QGroupBox(self.i2c_box)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spi_box.setFont(font)
        self.spi_box.setObjectName(_fromUtf8("spi_box"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.spi_box)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.base_SPI = hexSpinbox.HexSpinBox(self.spi_box)
        self.base_SPI.setSuffix(_fromUtf8(""))
        self.base_SPI.setPrefix(_fromUtf8(""))
        self.base_SPI.setMaximum(255)
        self.base_SPI.setProperty("value", 208)
        self.base_SPI.setObjectName(_fromUtf8("base_SPI"))
        self.verticalLayout_10.addWidget(self.base_SPI)
        self.reg_SPI = hexSpinbox.HexSpinBox(self.spi_box)
        self.reg_SPI.setSuffix(_fromUtf8(""))
        self.reg_SPI.setPrefix(_fromUtf8(""))
        self.reg_SPI.setMaximum(255)
        self.reg_SPI.setObjectName(_fromUtf8("reg_SPI"))
        self.verticalLayout_10.addWidget(self.reg_SPI)
        self.readbtn_SPI = QtGui.QPushButton(self.spi_box)
        self.readbtn_SPI.setObjectName(_fromUtf8("readbtn_SPI"))
        self.verticalLayout_10.addWidget(self.readbtn_SPI)
        self.read_SPI = hexSpinbox.HexSpinBox(self.spi_box)
        self.read_SPI.setEnabled(False)
        self.read_SPI.setSuffix(_fromUtf8(""))
        self.read_SPI.setPrefix(_fromUtf8(""))
        self.read_SPI.setMaximum(255)
        self.read_SPI.setObjectName(_fromUtf8("read_SPI"))
        self.verticalLayout_10.addWidget(self.read_SPI)
        self.writebtn_SPI = QtGui.QPushButton(self.spi_box)
        self.writebtn_SPI.setObjectName(_fromUtf8("writebtn_SPI"))
        self.verticalLayout_10.addWidget(self.writebtn_SPI)
        self.write_SPI = hexSpinbox.HexSpinBox(self.spi_box)
        self.write_SPI.setSuffix(_fromUtf8(""))
        self.write_SPI.setPrefix(_fromUtf8(""))
        self.write_SPI.setMaximum(255)
        self.write_SPI.setObjectName(_fromUtf8("write_SPI"))
        self.verticalLayout_10.addWidget(self.write_SPI)
        self.horizontalLayout_6.addWidget(self.spi_box)
        self.gridLayout.addWidget(self.i2c_box, 1, 0, 1, 1)
        self.regixters_box = QtGui.QGroupBox(Form)
        self.regixters_box.setObjectName(_fromUtf8("regixters_box"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.regixters_box)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.regixters_box)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.reg0_box = QtGui.QGroupBox(self.tab)
        self.reg0_box.setObjectName(_fromUtf8("reg0_box"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.reg0_box)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.reg07 = QtGui.QCheckBox(self.reg0_box)
        self.reg07.setEnabled(False)
        self.reg07.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.reg07.setObjectName(_fromUtf8("reg07"))
        self.horizontalLayout_2.addWidget(self.reg07)
        self.reg06 = QtGui.QCheckBox(self.reg0_box)
        self.reg06.setEnabled(False)
        self.reg06.setObjectName(_fromUtf8("reg06"))
        self.horizontalLayout_2.addWidget(self.reg06)
        self.reg05 = QtGui.QCheckBox(self.reg0_box)
        self.reg05.setEnabled(False)
        self.reg05.setObjectName(_fromUtf8("reg05"))
        self.horizontalLayout_2.addWidget(self.reg05)
        self.reg04 = QtGui.QCheckBox(self.reg0_box)
        self.reg04.setEnabled(False)
        self.reg04.setObjectName(_fromUtf8("reg04"))
        self.horizontalLayout_2.addWidget(self.reg04)
        self.reg03 = QtGui.QCheckBox(self.reg0_box)
        self.reg03.setEnabled(False)
        self.reg03.setObjectName(_fromUtf8("reg03"))
        self.horizontalLayout_2.addWidget(self.reg03)
        self.reg02 = QtGui.QCheckBox(self.reg0_box)
        self.reg02.setEnabled(False)
        self.reg02.setObjectName(_fromUtf8("reg02"))
        self.horizontalLayout_2.addWidget(self.reg02)
        self.reg01 = QtGui.QCheckBox(self.reg0_box)
        self.reg01.setEnabled(False)
        self.reg01.setObjectName(_fromUtf8("reg01"))
        self.horizontalLayout_2.addWidget(self.reg01)
        self.reg00 = QtGui.QCheckBox(self.reg0_box)
        self.reg00.setEnabled(False)
        self.reg00.setObjectName(_fromUtf8("reg00"))
        self.horizontalLayout_2.addWidget(self.reg00)
        self.readbtn_reg0 = QtGui.QPushButton(self.reg0_box)
        self.readbtn_reg0.setObjectName(_fromUtf8("readbtn_reg0"))
        self.horizontalLayout_2.addWidget(self.readbtn_reg0)
        self.read_reg0 = hexSpinbox.HexSpinBox(self.reg0_box)
        self.read_reg0.setEnabled(False)
        self.read_reg0.setMaximum(255)
        self.read_reg0.setObjectName(_fromUtf8("read_reg0"))
        self.horizontalLayout_2.addWidget(self.read_reg0)
        self.pushButton = QtGui.QPushButton(self.reg0_box)
        self.pushButton.setEnabled(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.spinBox = hexSpinbox.HexSpinBox(self.reg0_box)
        self.spinBox.setEnabled(False)
        self.spinBox.setMaximum(255)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.horizontalLayout_12.addWidget(self.reg0_box)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.groupBox_12 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.reg17 = QtGui.QCheckBox(self.groupBox_12)
        self.reg17.setObjectName(_fromUtf8("reg17"))
        self.horizontalLayout_3.addWidget(self.reg17)
        self.reg16 = QtGui.QCheckBox(self.groupBox_12)
        self.reg16.setObjectName(_fromUtf8("reg16"))
        self.horizontalLayout_3.addWidget(self.reg16)
        self.reg15 = QtGui.QCheckBox(self.groupBox_12)
        self.reg15.setObjectName(_fromUtf8("reg15"))
        self.horizontalLayout_3.addWidget(self.reg15)
        self.reg14 = QtGui.QCheckBox(self.groupBox_12)
        self.reg14.setObjectName(_fromUtf8("reg14"))
        self.horizontalLayout_3.addWidget(self.reg14)
        self.reg13 = QtGui.QCheckBox(self.groupBox_12)
        self.reg13.setObjectName(_fromUtf8("reg13"))
        self.horizontalLayout_3.addWidget(self.reg13)
        self.reg12 = QtGui.QCheckBox(self.groupBox_12)
        self.reg12.setObjectName(_fromUtf8("reg12"))
        self.horizontalLayout_3.addWidget(self.reg12)
        self.reg11 = QtGui.QCheckBox(self.groupBox_12)
        self.reg11.setObjectName(_fromUtf8("reg11"))
        self.horizontalLayout_3.addWidget(self.reg11)
        self.reg10 = QtGui.QCheckBox(self.groupBox_12)
        self.reg10.setObjectName(_fromUtf8("reg10"))
        self.horizontalLayout_3.addWidget(self.reg10)
        self.readbtn_reg1 = QtGui.QPushButton(self.groupBox_12)
        self.readbtn_reg1.setObjectName(_fromUtf8("readbtn_reg1"))
        self.horizontalLayout_3.addWidget(self.readbtn_reg1)
        self.read_reg1 = hexSpinbox.HexSpinBox(self.groupBox_12)
        self.read_reg1.setEnabled(False)
        self.read_reg1.setMaximum(255)
        self.read_reg1.setObjectName(_fromUtf8("read_reg1"))
        self.horizontalLayout_3.addWidget(self.read_reg1)
        self.writebtn_reg1 = QtGui.QPushButton(self.groupBox_12)
        self.writebtn_reg1.setObjectName(_fromUtf8("writebtn_reg1"))
        self.horizontalLayout_3.addWidget(self.writebtn_reg1)
        self.write_reg1 = hexSpinbox.HexSpinBox(self.groupBox_12)
        self.write_reg1.setMaximum(255)
        self.write_reg1.setObjectName(_fromUtf8("write_reg1"))
        self.horizontalLayout_3.addWidget(self.write_reg1)
        self.horizontalLayout_11.addWidget(self.groupBox_12)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_14 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_14.setEnabled(False)
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.reg27 = QtGui.QCheckBox(self.groupBox_14)
        self.reg27.setObjectName(_fromUtf8("reg27"))
        self.horizontalLayout_4.addWidget(self.reg27)
        self.reg26 = QtGui.QCheckBox(self.groupBox_14)
        self.reg26.setObjectName(_fromUtf8("reg26"))
        self.horizontalLayout_4.addWidget(self.reg26)
        self.reg25 = QtGui.QCheckBox(self.groupBox_14)
        self.reg25.setObjectName(_fromUtf8("reg25"))
        self.horizontalLayout_4.addWidget(self.reg25)
        self.reg24 = QtGui.QCheckBox(self.groupBox_14)
        self.reg24.setObjectName(_fromUtf8("reg24"))
        self.horizontalLayout_4.addWidget(self.reg24)
        self.reg23 = QtGui.QCheckBox(self.groupBox_14)
        self.reg23.setObjectName(_fromUtf8("reg23"))
        self.horizontalLayout_4.addWidget(self.reg23)
        self.reg22 = QtGui.QCheckBox(self.groupBox_14)
        self.reg22.setObjectName(_fromUtf8("reg22"))
        self.horizontalLayout_4.addWidget(self.reg22)
        self.reg21 = QtGui.QCheckBox(self.groupBox_14)
        self.reg21.setObjectName(_fromUtf8("reg21"))
        self.horizontalLayout_4.addWidget(self.reg21)
        self.reg20 = QtGui.QCheckBox(self.groupBox_14)
        self.reg20.setObjectName(_fromUtf8("reg20"))
        self.horizontalLayout_4.addWidget(self.reg20)
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_14)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_4.addWidget(self.pushButton_7)
        self.spinBox_4 = hexSpinbox.HexSpinBox(self.groupBox_14)
        self.spinBox_4.setEnabled(False)
        self.spinBox_4.setMaximum(255)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.horizontalLayout_4.addWidget(self.spinBox_4)
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_14)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_4.addWidget(self.pushButton_8)
        self.spinBox_11 = hexSpinbox.HexSpinBox(self.groupBox_14)
        self.spinBox_11.setMaximum(255)
        self.spinBox_11.setObjectName(_fromUtf8("spinBox_11"))
        self.horizontalLayout_4.addWidget(self.spinBox_11)
        self.verticalLayout_3.addWidget(self.groupBox_14)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.groupBox_13 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.reg37 = QtGui.QCheckBox(self.groupBox_13)
        self.reg37.setObjectName(_fromUtf8("reg37"))
        self.horizontalLayout_5.addWidget(self.reg37)
        self.reg36 = QtGui.QCheckBox(self.groupBox_13)
        self.reg36.setObjectName(_fromUtf8("reg36"))
        self.horizontalLayout_5.addWidget(self.reg36)
        self.reg35 = QtGui.QCheckBox(self.groupBox_13)
        self.reg35.setObjectName(_fromUtf8("reg35"))
        self.horizontalLayout_5.addWidget(self.reg35)
        self.reg34 = QtGui.QCheckBox(self.groupBox_13)
        self.reg34.setObjectName(_fromUtf8("reg34"))
        self.horizontalLayout_5.addWidget(self.reg34)
        self.reg33 = QtGui.QCheckBox(self.groupBox_13)
        self.reg33.setObjectName(_fromUtf8("reg33"))
        self.horizontalLayout_5.addWidget(self.reg33)
        self.reg32 = QtGui.QCheckBox(self.groupBox_13)
        self.reg32.setObjectName(_fromUtf8("reg32"))
        self.horizontalLayout_5.addWidget(self.reg32)
        self.reg31 = QtGui.QCheckBox(self.groupBox_13)
        self.reg31.setObjectName(_fromUtf8("reg31"))
        self.horizontalLayout_5.addWidget(self.reg31)
        self.reg30 = QtGui.QCheckBox(self.groupBox_13)
        self.reg30.setObjectName(_fromUtf8("reg30"))
        self.horizontalLayout_5.addWidget(self.reg30)
        self.readbtn_reg3 = QtGui.QPushButton(self.groupBox_13)
        self.readbtn_reg3.setObjectName(_fromUtf8("readbtn_reg3"))
        self.horizontalLayout_5.addWidget(self.readbtn_reg3)
        self.read_reg3 = hexSpinbox.HexSpinBox(self.groupBox_13)
        self.read_reg3.setEnabled(False)
        self.read_reg3.setMaximum(255)
        self.read_reg3.setObjectName(_fromUtf8("read_reg3"))
        self.horizontalLayout_5.addWidget(self.read_reg3)
        self.writebtn_reg3 = QtGui.QPushButton(self.groupBox_13)
        self.writebtn_reg3.setObjectName(_fromUtf8("writebtn_reg3"))
        self.horizontalLayout_5.addWidget(self.writebtn_reg3)
        self.write_reg3 = hexSpinbox.HexSpinBox(self.groupBox_13)
        self.write_reg3.setMaximum(255)
        self.write_reg3.setObjectName(_fromUtf8("write_reg3"))
        self.horizontalLayout_5.addWidget(self.write_reg3)
        self.horizontalLayout_14.addWidget(self.groupBox_13)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.tab_5)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.groupBox_18 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_18.setEnabled(False)
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_18)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.checkBox_57 = QtGui.QCheckBox(self.groupBox_18)
        self.checkBox_57.setObjectName(_fromUtf8("checkBox_57"))
        self.horizontalLayout_7.addWidget(self.checkBox_57)
        self.checkBox_58 = QtGui.QCheckBox(self.groupBox_18)
        self.checkBox_58.setObjectName(_fromUtf8("checkBox_58"))
        self.horizontalLayout_7.addWidget(self.checkBox_58)
        self.checkBox_59 = QtGui.QCheckBox(self.groupBox_18)
        self.checkBox_59.setObjectName(_fromUtf8("checkBox_59"))
        self.horizontalLayout_7.addWidget(self.checkBox_59)
        self.checkBox_60 = QtGui.QCheckBox(self.groupBox_18)
        self.checkBox_60.setObjectName(_fromUtf8("checkBox_60"))
        self.horizontalLayout_7.addWidget(self.checkBox_60)
        self.checkBox_61 = QtGui.QCheckBox(self.groupBox_18)
        self.checkBox_61.setObjectName(_fromUtf8("checkBox_61"))
        self.horizontalLayout_7.addWidget(self.checkBox_61)
        self.checkBox_62 = QtGui.QCheckBox(self.groupBox_18)
        self.checkBox_62.setObjectName(_fromUtf8("checkBox_62"))
        self.horizontalLayout_7.addWidget(self.checkBox_62)
        self.checkBox_63 = QtGui.QCheckBox(self.groupBox_18)
        self.checkBox_63.setObjectName(_fromUtf8("checkBox_63"))
        self.horizontalLayout_7.addWidget(self.checkBox_63)
        self.checkBox_64 = QtGui.QCheckBox(self.groupBox_18)
        self.checkBox_64.setObjectName(_fromUtf8("checkBox_64"))
        self.horizontalLayout_7.addWidget(self.checkBox_64)
        self.pushButton_15 = QtGui.QPushButton(self.groupBox_18)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.horizontalLayout_7.addWidget(self.pushButton_15)
        self.spinBox_8 = hexSpinbox.HexSpinBox(self.groupBox_18)
        self.spinBox_8.setEnabled(False)
        self.spinBox_8.setMaximum(255)
        self.spinBox_8.setObjectName(_fromUtf8("spinBox_8"))
        self.horizontalLayout_7.addWidget(self.spinBox_8)
        self.pushButton_16 = QtGui.QPushButton(self.groupBox_18)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.horizontalLayout_7.addWidget(self.pushButton_16)
        self.spinBox_13 = hexSpinbox.HexSpinBox(self.groupBox_18)
        self.spinBox_13.setMaximum(255)
        self.spinBox_13.setObjectName(_fromUtf8("spinBox_13"))
        self.horizontalLayout_7.addWidget(self.spinBox_13)
        self.horizontalLayout_15.addWidget(self.groupBox_18)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.tab_6)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.groupBox_17 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_17.setEnabled(False)
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_17)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.checkBox_49 = QtGui.QCheckBox(self.groupBox_17)
        self.checkBox_49.setObjectName(_fromUtf8("checkBox_49"))
        self.horizontalLayout_8.addWidget(self.checkBox_49)
        self.checkBox_50 = QtGui.QCheckBox(self.groupBox_17)
        self.checkBox_50.setObjectName(_fromUtf8("checkBox_50"))
        self.horizontalLayout_8.addWidget(self.checkBox_50)
        self.checkBox_51 = QtGui.QCheckBox(self.groupBox_17)
        self.checkBox_51.setObjectName(_fromUtf8("checkBox_51"))
        self.horizontalLayout_8.addWidget(self.checkBox_51)
        self.checkBox_52 = QtGui.QCheckBox(self.groupBox_17)
        self.checkBox_52.setObjectName(_fromUtf8("checkBox_52"))
        self.horizontalLayout_8.addWidget(self.checkBox_52)
        self.checkBox_53 = QtGui.QCheckBox(self.groupBox_17)
        self.checkBox_53.setObjectName(_fromUtf8("checkBox_53"))
        self.horizontalLayout_8.addWidget(self.checkBox_53)
        self.checkBox_54 = QtGui.QCheckBox(self.groupBox_17)
        self.checkBox_54.setObjectName(_fromUtf8("checkBox_54"))
        self.horizontalLayout_8.addWidget(self.checkBox_54)
        self.checkBox_55 = QtGui.QCheckBox(self.groupBox_17)
        self.checkBox_55.setObjectName(_fromUtf8("checkBox_55"))
        self.horizontalLayout_8.addWidget(self.checkBox_55)
        self.checkBox_56 = QtGui.QCheckBox(self.groupBox_17)
        self.checkBox_56.setObjectName(_fromUtf8("checkBox_56"))
        self.horizontalLayout_8.addWidget(self.checkBox_56)
        self.pushButton_13 = QtGui.QPushButton(self.groupBox_17)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.horizontalLayout_8.addWidget(self.pushButton_13)
        self.spinBox_7 = hexSpinbox.HexSpinBox(self.groupBox_17)
        self.spinBox_7.setEnabled(False)
        self.spinBox_7.setMaximum(255)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.horizontalLayout_8.addWidget(self.spinBox_7)
        self.pushButton_14 = QtGui.QPushButton(self.groupBox_17)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.horizontalLayout_8.addWidget(self.pushButton_14)
        self.spinBox_14 = hexSpinbox.HexSpinBox(self.groupBox_17)
        self.spinBox_14.setMaximum(255)
        self.spinBox_14.setObjectName(_fromUtf8("spinBox_14"))
        self.horizontalLayout_8.addWidget(self.spinBox_14)
        self.horizontalLayout_16.addWidget(self.groupBox_17)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.tab_7)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.groupBox_16 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_16.setEnabled(False)
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_16)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.checkBox_41 = QtGui.QCheckBox(self.groupBox_16)
        self.checkBox_41.setObjectName(_fromUtf8("checkBox_41"))
        self.horizontalLayout_9.addWidget(self.checkBox_41)
        self.checkBox_42 = QtGui.QCheckBox(self.groupBox_16)
        self.checkBox_42.setObjectName(_fromUtf8("checkBox_42"))
        self.horizontalLayout_9.addWidget(self.checkBox_42)
        self.checkBox_43 = QtGui.QCheckBox(self.groupBox_16)
        self.checkBox_43.setObjectName(_fromUtf8("checkBox_43"))
        self.horizontalLayout_9.addWidget(self.checkBox_43)
        self.checkBox_44 = QtGui.QCheckBox(self.groupBox_16)
        self.checkBox_44.setObjectName(_fromUtf8("checkBox_44"))
        self.horizontalLayout_9.addWidget(self.checkBox_44)
        self.checkBox_45 = QtGui.QCheckBox(self.groupBox_16)
        self.checkBox_45.setObjectName(_fromUtf8("checkBox_45"))
        self.horizontalLayout_9.addWidget(self.checkBox_45)
        self.checkBox_46 = QtGui.QCheckBox(self.groupBox_16)
        self.checkBox_46.setObjectName(_fromUtf8("checkBox_46"))
        self.horizontalLayout_9.addWidget(self.checkBox_46)
        self.checkBox_47 = QtGui.QCheckBox(self.groupBox_16)
        self.checkBox_47.setObjectName(_fromUtf8("checkBox_47"))
        self.horizontalLayout_9.addWidget(self.checkBox_47)
        self.checkBox_48 = QtGui.QCheckBox(self.groupBox_16)
        self.checkBox_48.setObjectName(_fromUtf8("checkBox_48"))
        self.horizontalLayout_9.addWidget(self.checkBox_48)
        self.pushButton_11 = QtGui.QPushButton(self.groupBox_16)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout_9.addWidget(self.pushButton_11)
        self.spinBox_6 = hexSpinbox.HexSpinBox(self.groupBox_16)
        self.spinBox_6.setEnabled(False)
        self.spinBox_6.setMaximum(255)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.horizontalLayout_9.addWidget(self.spinBox_6)
        self.pushButton_12 = QtGui.QPushButton(self.groupBox_16)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.horizontalLayout_9.addWidget(self.pushButton_12)
        self.spinBox_15 = hexSpinbox.HexSpinBox(self.groupBox_16)
        self.spinBox_15.setMaximum(255)
        self.spinBox_15.setObjectName(_fromUtf8("spinBox_15"))
        self.horizontalLayout_9.addWidget(self.spinBox_15)
        self.horizontalLayout_17.addWidget(self.groupBox_16)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.tab_8)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.groupBox_15 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_15.setEnabled(False)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox_15)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.checkBox_33 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_33.setObjectName(_fromUtf8("checkBox_33"))
        self.horizontalLayout_10.addWidget(self.checkBox_33)
        self.checkBox_34 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_34.setObjectName(_fromUtf8("checkBox_34"))
        self.horizontalLayout_10.addWidget(self.checkBox_34)
        self.checkBox_35 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_35.setObjectName(_fromUtf8("checkBox_35"))
        self.horizontalLayout_10.addWidget(self.checkBox_35)
        self.checkBox_36 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_36.setObjectName(_fromUtf8("checkBox_36"))
        self.horizontalLayout_10.addWidget(self.checkBox_36)
        self.checkBox_37 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_37.setObjectName(_fromUtf8("checkBox_37"))
        self.horizontalLayout_10.addWidget(self.checkBox_37)
        self.checkBox_38 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_38.setObjectName(_fromUtf8("checkBox_38"))
        self.horizontalLayout_10.addWidget(self.checkBox_38)
        self.checkBox_39 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_39.setObjectName(_fromUtf8("checkBox_39"))
        self.horizontalLayout_10.addWidget(self.checkBox_39)
        self.checkBox_40 = QtGui.QCheckBox(self.groupBox_15)
        self.checkBox_40.setObjectName(_fromUtf8("checkBox_40"))
        self.horizontalLayout_10.addWidget(self.checkBox_40)
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_15)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_10.addWidget(self.pushButton_9)
        self.spinBox_5 = hexSpinbox.HexSpinBox(self.groupBox_15)
        self.spinBox_5.setEnabled(False)
        self.spinBox_5.setMaximum(255)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.horizontalLayout_10.addWidget(self.spinBox_5)
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_15)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout_10.addWidget(self.pushButton_10)
        self.spinBox_16 = hexSpinbox.HexSpinBox(self.groupBox_15)
        self.spinBox_16.setMaximum(255)
        self.spinBox_16.setObjectName(_fromUtf8("spinBox_16"))
        self.horizontalLayout_10.addWidget(self.spinBox_16)
        self.horizontalLayout_18.addWidget(self.groupBox_15)
        self.tabWidget.addTab(self.tab_8, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.gridLayout.addWidget(self.regixters_box, 2, 0, 1, 1)

        self.retranslateUi(Form)
        self.portList.setCurrentIndex(-1)
#        self.tabWidget.setCurrentIndex(7)
#        QtCore.QObject.connect(self.getPortBtn, QtCore.SIGNAL(_fromUtf8("clicked()")), self.portList.clear)
#        QtCore.QObject.connect(self.readbtn_CH2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.read_CH2.clear)
#        QtCore.QObject.connect(self.base_CH3, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.base_CH3.clear)
#        QtCore.QObject.connect(self.readbtn_CH4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.read_CH4.clear)
#        QtCore.QObject.connect(self.base_CH2, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.base_CH2.clear)
#        QtCore.QObject.connect(self.reg_CH1, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.reg_CH1.clear)
#        QtCore.QObject.connect(self.readbtn_CH3, QtCore.SIGNAL(_fromUtf8("clicked()")), self.read_CH3.clear)
#        QtCore.QObject.connect(self.reg_CH2, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.reg_CH2.clear)
#        QtCore.QObject.connect(self.readbtn_CH1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.read_CH1.clear)
#        QtCore.QObject.connect(self.writebtn_CH1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.write_CH1.clear)
#        QtCore.QObject.connect(self.writebtn_CH3, QtCore.SIGNAL(_fromUtf8("clicked()")), self.write_CH3.clear)
#        QtCore.QObject.connect(self.writebtn_CH2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.write_CH2.clear)
#        QtCore.QObject.connect(self.writebtn_CH4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.write_CH4.clear)
#        QtCore.QObject.connect(self.base_CH1, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.base_CH1.clear)
#        QtCore.QObject.connect(self.reg_CH3, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.reg_CH3.clear)
#        QtCore.QObject.connect(self.base_CH4, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.base_CH4.clear)
#        QtCore.QObject.connect(self.reg_CH4, QtCore.SIGNAL(_fromUtf8("editingFinished()")), self.reg_CH4.clear)
#        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "TinyI2C", None))
        self.conport_box.setTitle(_translate("Form", "COM port", None))
        self.getPortBtn.setText(_translate("Form", "Search", None))
        self.log_box.setTitle(_translate("Form", "Log message", None))
        self.log_text.setPlainText(_translate("Form", "This is \n"
        "a\n"
        "log message\n"
        "window", None))
        self.i2c_box.setTitle(_translate("Form", "Interfaces", None))
        self.i2c1_box.setTitle(_translate("Form", "I2C0", None))
        self.readbtn_CH1.setText(_translate("Form", "Read", None))
        self.writebtn_CH1.setText(_translate("Form", "Write", None))
        self.i2c2_box.setTitle(_translate("Form", "I2C1", None))
        self.readbtn_CH2.setText(_translate("Form", "Read", None))
        self.writebtn_CH2.setText(_translate("Form", "Write", None))
        self.i2c3_box.setTitle(_translate("Form", "I2C2", None))
        self.readbtn_CH3.setText(_translate("Form", "Read", None))
        self.writebtn_CH3.setText(_translate("Form", "Write", None))
        self.i2c4_box.setTitle(_translate("Form", "I2C3", None))
        self.readbtn_CH4.setText(_translate("Form", "Read", None))
        self.writebtn_CH4.setText(_translate("Form", "Write", None))
        self.spi_box.setTitle(_translate("Form", "SPI", None))
        self.readbtn_SPI.setText(_translate("Form", "Read", None))
        self.writebtn_SPI.setText(_translate("Form", "Write", None))
        self.regixters_box.setTitle(_translate("Form", "Registers", None))
        self.reg0_box.setTitle(_translate("Form", "Register 0", None))
        self.reg07.setText(_translate("Form", "7", None))
        self.reg06.setText(_translate("Form", "6", None))
        self.reg05.setText(_translate("Form", "5", None))
        self.reg04.setText(_translate("Form", "4", None))
        self.reg03.setText(_translate("Form", "3", None))
        self.reg02.setText(_translate("Form", "2", None))
        self.reg01.setText(_translate("Form", "1", None))
        self.reg00.setText(_translate("Form", "0", None))
        self.readbtn_reg0.setText(_translate("Form", "Read", None))
        self.pushButton.setText(_translate("Form", "Write", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "0", None))
        self.groupBox_12.setTitle(_translate("Form", "Register 1", None))
        self.reg17.setText(_translate("Form", "7", None))
        self.reg16.setText(_translate("Form", "6", None))
        self.reg15.setText(_translate("Form", "5", None))
        self.reg14.setText(_translate("Form", "4", None))
        self.reg13.setText(_translate("Form", "3", None))
        self.reg12.setText(_translate("Form", "2", None))
        self.reg11.setText(_translate("Form", "1", None))
        self.reg10.setText(_translate("Form", "0", None))
        self.readbtn_reg1.setText(_translate("Form", "Read", None))
        self.writebtn_reg1.setText(_translate("Form", "Write", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "1", None))
        self.groupBox_14.setTitle(_translate("Form", "Register 2", None))
        self.reg27.setText(_translate("Form", "7", None))
        self.reg26.setText(_translate("Form", "6", None))
        self.reg25.setText(_translate("Form", "5", None))
        self.reg24.setText(_translate("Form", "4", None))
        self.reg23.setText(_translate("Form", "3", None))
        self.reg22.setText(_translate("Form", "2", None))
        self.reg21.setText(_translate("Form", "1", None))
        self.reg20.setText(_translate("Form", "0", None))
        self.pushButton_7.setText(_translate("Form", "Read", None))
        self.pushButton_8.setText(_translate("Form", "Write", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "2", None))
        self.groupBox_13.setTitle(_translate("Form", "Register 3", None))
        self.reg37.setText(_translate("Form", "7", None))
        self.reg36.setText(_translate("Form", "6", None))
        self.reg35.setText(_translate("Form", "5", None))
        self.reg34.setText(_translate("Form", "4", None))
        self.reg33.setText(_translate("Form", "3", None))
        self.reg32.setText(_translate("Form", "2", None))
        self.reg31.setText(_translate("Form", "1", None))
        self.reg30.setText(_translate("Form", "0", None))
        self.readbtn_reg3.setText(_translate("Form", "Read", None))
        self.writebtn_reg3.setText(_translate("Form", "Write", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "3", None))
        self.groupBox_18.setTitle(_translate("Form", "Register 4", None))
        self.checkBox_57.setText(_translate("Form", "7", None))
        self.checkBox_58.setText(_translate("Form", "6", None))
        self.checkBox_59.setText(_translate("Form", "5", None))
        self.checkBox_60.setText(_translate("Form", "4", None))
        self.checkBox_61.setText(_translate("Form", "3", None))
        self.checkBox_62.setText(_translate("Form", "2", None))
        self.checkBox_63.setText(_translate("Form", "1", None))
        self.checkBox_64.setText(_translate("Form", "0", None))
        self.pushButton_15.setText(_translate("Form", "Read", None))
        self.pushButton_16.setText(_translate("Form", "Write", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "4", None))
        self.groupBox_17.setTitle(_translate("Form", "Register 5", None))
        self.checkBox_49.setText(_translate("Form", "7", None))
        self.checkBox_50.setText(_translate("Form", "6", None))
        self.checkBox_51.setText(_translate("Form", "5", None))
        self.checkBox_52.setText(_translate("Form", "4", None))
        self.checkBox_53.setText(_translate("Form", "3", None))
        self.checkBox_54.setText(_translate("Form", "2", None))
        self.checkBox_55.setText(_translate("Form", "1", None))
        self.checkBox_56.setText(_translate("Form", "0", None))
        self.pushButton_13.setText(_translate("Form", "Read", None))
        self.pushButton_14.setText(_translate("Form", "Write", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Form", "5", None))
        self.groupBox_16.setTitle(_translate("Form", "Register 6", None))
        self.checkBox_41.setText(_translate("Form", "7", None))
        self.checkBox_42.setText(_translate("Form", "6", None))
        self.checkBox_43.setText(_translate("Form", "5", None))
        self.checkBox_44.setText(_translate("Form", "4", None))
        self.checkBox_45.setText(_translate("Form", "3", None))
        self.checkBox_46.setText(_translate("Form", "2", None))
        self.checkBox_47.setText(_translate("Form", "1", None))
        self.checkBox_48.setText(_translate("Form", "0", None))
        self.pushButton_11.setText(_translate("Form", "Read", None))
        self.pushButton_12.setText(_translate("Form", "Write", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Form", "6", None))
        self.groupBox_15.setTitle(_translate("Form", "Register 7", None))
        self.checkBox_33.setText(_translate("Form", "7", None))
        self.checkBox_34.setText(_translate("Form", "6", None))
        self.checkBox_35.setText(_translate("Form", "5", None))
        self.checkBox_36.setText(_translate("Form", "4", None))
        self.checkBox_37.setText(_translate("Form", "3", None))
        self.checkBox_38.setText(_translate("Form", "2", None))
        self.checkBox_39.setText(_translate("Form", "1", None))
        self.checkBox_40.setText(_translate("Form", "0", None))
        self.pushButton_9.setText(_translate("Form", "Read", None))
        self.pushButton_10.setText(_translate("Form", "Write", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("Form", "7", None))


#if __name__ == "__main__":
#    import sys
#    app = QtGui.QApplication(sys.argv)
#    Form = QtGui.QWidget()
#    ui = Ui_Form()
#    ui.setupUi(Form)
#    Form.show()
#    sys.exit(app.exec_())

