# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tinyI2C.ui'
#
# Created: Tue Jan 06 19:44:21 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
#from hexSpinbox import *
import hexSpinbox

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(480, 320)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.getPortBtn = QtGui.QPushButton(self.groupBox)
        self.getPortBtn.setObjectName(_fromUtf8("getPortBtn"))
        self.horizontalLayout.addWidget(self.getPortBtn)
        self.portList = QtGui.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.portList.setFont(font)
        self.portList.setObjectName(_fromUtf8("portList"))
        self.horizontalLayout.addWidget(self.portList)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox_2 = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.base_CH1 = hexSpinbox.HexSpinBox(self.groupBox_2)
        self.base_CH1.setSuffix(_fromUtf8(""))
        self.base_CH1.setMaximum(255)
        self.base_CH1.setProperty("value", 208)
        self.base_CH1.setObjectName(_fromUtf8("base_CH1"))
        self.verticalLayout.addWidget(self.base_CH1)
        self.reg_CH1 = hexSpinbox.HexSpinBox(self.groupBox_2)
        self.reg_CH1.setSuffix(_fromUtf8(""))
        self.reg_CH1.setMaximum(255)
        self.reg_CH1.setObjectName(_fromUtf8("reg_CH1"))
        self.verticalLayout.addWidget(self.reg_CH1)
        self.readbtn_CH1 = QtGui.QPushButton(self.groupBox_2)
        self.readbtn_CH1.setObjectName(_fromUtf8("readbtn_CH1"))
        self.verticalLayout.addWidget(self.readbtn_CH1)
        self.read_CH1 = hexSpinbox.HexSpinBox(self.groupBox_2)
        self.read_CH1.setEnabled(False)
        self.read_CH1.setSuffix(_fromUtf8(""))
        self.read_CH1.setMaximum(255)
        self.read_CH1.setObjectName(_fromUtf8("read_CH1"))
        self.verticalLayout.addWidget(self.read_CH1)
        self.writebtn_CH1 = QtGui.QPushButton(self.groupBox_2)
        self.writebtn_CH1.setObjectName(_fromUtf8("writebtn_CH1"))
        self.verticalLayout.addWidget(self.writebtn_CH1)
        self.write_CH1 = hexSpinbox.HexSpinBox(self.groupBox_2)
        self.write_CH1.setSuffix(_fromUtf8(""))
        self.write_CH1.setMaximum(255)
        self.write_CH1.setObjectName(_fromUtf8("write_CH1"))
        self.verticalLayout.addWidget(self.write_CH1)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.base_CH2 = hexSpinbox.HexSpinBox(self.groupBox_3)
        self.base_CH2.setSuffix(_fromUtf8(""))
        self.base_CH2.setMaximum(255)
        self.base_CH2.setProperty("value", 208)
        self.base_CH2.setObjectName(_fromUtf8("base_CH2"))
        self.verticalLayout_5.addWidget(self.base_CH2)
        self.reg_CH2 = hexSpinbox.HexSpinBox(self.groupBox_3)
        self.reg_CH2.setSuffix(_fromUtf8(""))
        self.reg_CH2.setMaximum(255)
        self.reg_CH2.setObjectName(_fromUtf8("reg_CH2"))
        self.verticalLayout_5.addWidget(self.reg_CH2)
        self.readbtn_CH2 = QtGui.QPushButton(self.groupBox_3)
        self.readbtn_CH2.setObjectName(_fromUtf8("readbtn_CH2"))
        self.verticalLayout_5.addWidget(self.readbtn_CH2)
        self.read_CH2 = hexSpinbox.HexSpinBox(self.groupBox_3)
        self.read_CH2.setEnabled(False)
        self.read_CH2.setSuffix(_fromUtf8(""))
        self.read_CH2.setMaximum(255)
        self.read_CH2.setObjectName(_fromUtf8("read_CH2"))
        self.verticalLayout_5.addWidget(self.read_CH2)
        self.writebtn_CH2 = QtGui.QPushButton(self.groupBox_3)
        self.writebtn_CH2.setObjectName(_fromUtf8("writebtn_CH2"))
        self.verticalLayout_5.addWidget(self.writebtn_CH2)
        self.write_CH2 = hexSpinbox.HexSpinBox(self.groupBox_3)
        self.write_CH2.setSuffix(_fromUtf8(""))
        self.write_CH2.setMaximum(255)
        self.write_CH2.setObjectName(_fromUtf8("write_CH2"))
        self.verticalLayout_5.addWidget(self.write_CH2)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.base_CH3 = hexSpinbox.HexSpinBox(self.groupBox_4)
        self.base_CH3.setSuffix(_fromUtf8(""))
        self.base_CH3.setMaximum(255)
        self.base_CH3.setProperty("value", 208)
        self.base_CH3.setObjectName(_fromUtf8("base_CH3"))
        self.verticalLayout_6.addWidget(self.base_CH3)
        self.reg_CH3 = hexSpinbox.HexSpinBox(self.groupBox_4)
        self.reg_CH3.setSuffix(_fromUtf8(""))
        self.reg_CH3.setMaximum(255)
        self.reg_CH3.setObjectName(_fromUtf8("reg_CH3"))
        self.verticalLayout_6.addWidget(self.reg_CH3)
        self.readbtn_CH3 = QtGui.QPushButton(self.groupBox_4)
        self.readbtn_CH3.setObjectName(_fromUtf8("readbtn_CH3"))
        self.verticalLayout_6.addWidget(self.readbtn_CH3)
        self.read_CH3 = hexSpinbox.HexSpinBox(self.groupBox_4)
        self.read_CH3.setEnabled(False)
        self.read_CH3.setSuffix(_fromUtf8(""))
        self.read_CH3.setMaximum(255)
        self.read_CH3.setObjectName(_fromUtf8("read_CH3"))
        self.verticalLayout_6.addWidget(self.read_CH3)
        self.writebtn_CH3 = QtGui.QPushButton(self.groupBox_4)
        self.writebtn_CH3.setObjectName(_fromUtf8("writebtn_CH3"))
        self.verticalLayout_6.addWidget(self.writebtn_CH3)
        self.write_CH3 = hexSpinbox.HexSpinBox(self.groupBox_4)
        self.write_CH3.setSuffix(_fromUtf8(""))
        self.write_CH3.setMaximum(255)
        self.write_CH3.setObjectName(_fromUtf8("write_CH3"))
        self.verticalLayout_6.addWidget(self.write_CH3)
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.base_CH4 = hexSpinbox.HexSpinBox(self.groupBox_5)
        self.base_CH4.setSuffix(_fromUtf8(""))
        self.base_CH4.setMaximum(255)
        self.base_CH4.setProperty("value", 208)
        self.base_CH4.setObjectName(_fromUtf8("base_CH4"))
        self.verticalLayout_7.addWidget(self.base_CH4)
        self.reg_CH4 = hexSpinbox.HexSpinBox(self.groupBox_5)
        self.reg_CH4.setSuffix(_fromUtf8(""))
        self.reg_CH4.setMaximum(255)
        self.reg_CH4.setObjectName(_fromUtf8("reg_CH4"))
        self.verticalLayout_7.addWidget(self.reg_CH4)
        self.readbtn_CH4 = QtGui.QPushButton(self.groupBox_5)
        self.readbtn_CH4.setObjectName(_fromUtf8("readbtn_CH4"))
        self.verticalLayout_7.addWidget(self.readbtn_CH4)
        self.read_CH4 = hexSpinbox.HexSpinBox(self.groupBox_5)
        self.read_CH4.setEnabled(False)
        self.read_CH4.setSuffix(_fromUtf8(""))
        self.read_CH4.setMaximum(255)
        self.read_CH4.setObjectName(_fromUtf8("read_CH4"))
        self.verticalLayout_7.addWidget(self.read_CH4)
        self.writebtn_CH4 = QtGui.QPushButton(self.groupBox_5)
        self.writebtn_CH4.setObjectName(_fromUtf8("writebtn_CH4"))
        self.verticalLayout_7.addWidget(self.writebtn_CH4)
        self.write_CH4 = hexSpinbox.HexSpinBox(self.groupBox_5)
        self.write_CH4.setSuffix(_fromUtf8(""))
        self.write_CH4.setMaximum(255)
        self.write_CH4.setObjectName(_fromUtf8("write_CH4"))
        self.verticalLayout_7.addWidget(self.write_CH4)
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        self.portList.setCurrentIndex(-1)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "TinyI2C", None))
        self.groupBox.setTitle(_translate("Form", "tinyI2C port", None))
        self.getPortBtn.setText(_translate("Form", "Search", None))
        self.groupBox_2.setTitle(_translate("Form", "CH1", None))
        self.base_CH1.setPrefix(_translate("Form", "0x", None))
        self.reg_CH1.setPrefix(_translate("Form", "0x", None))
        self.readbtn_CH1.setText(_translate("Form", "Read", None))
        self.read_CH1.setPrefix(_translate("Form", "0x", None))
        self.writebtn_CH1.setText(_translate("Form", "Write", None))
        self.write_CH1.setPrefix(_translate("Form", "0x", None))
        self.groupBox_3.setTitle(_translate("Form", "CH2", None))
        self.base_CH2.setPrefix(_translate("Form", "0x", None))
        self.reg_CH2.setPrefix(_translate("Form", "0x", None))
        self.readbtn_CH2.setText(_translate("Form", "Read", None))
        self.read_CH2.setPrefix(_translate("Form", "0x", None))
        self.writebtn_CH2.setText(_translate("Form", "Write", None))
        self.write_CH2.setPrefix(_translate("Form", "0x", None))
        self.groupBox_4.setTitle(_translate("Form", "CH3", None))
        self.base_CH3.setPrefix(_translate("Form", "0x", None))
        self.reg_CH3.setPrefix(_translate("Form", "0x", None))
        self.readbtn_CH3.setText(_translate("Form", "Read", None))
        self.read_CH3.setPrefix(_translate("Form", "0x", None))
        self.writebtn_CH3.setText(_translate("Form", "Write", None))
        self.write_CH3.setPrefix(_translate("Form", "0x", None))
        self.groupBox_5.setTitle(_translate("Form", "CH4", None))
        self.base_CH4.setPrefix(_translate("Form", "0x", None))
        self.reg_CH4.setPrefix(_translate("Form", "0x", None))
        self.readbtn_CH4.setText(_translate("Form", "Read", None))
        self.read_CH4.setPrefix(_translate("Form", "0x", None))
        self.writebtn_CH4.setText(_translate("Form", "Write", None))
        self.write_CH4.setPrefix(_translate("Form", "0x", None))

